/*
 * Katalon TestOps API reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.katalon.testops.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.katalon.testops.model.ExecutionTestResultResource;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * TestResultAssertionFailedResource
 */


public class TestResultAssertionFailedResource {
  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("executionTestResultId")
  private Long executionTestResultId = null;

  @JsonProperty("executionTestResultResource")
  private ExecutionTestResultResource executionTestResultResource = null;

  @JsonProperty("stacktrace")
  private String stacktrace = null;

  @JsonProperty("message")
  private String message = null;

  @JsonProperty("logTime")
  private String logTime = null;

  public TestResultAssertionFailedResource id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public TestResultAssertionFailedResource executionTestResultId(Long executionTestResultId) {
    this.executionTestResultId = executionTestResultId;
    return this;
  }

   /**
   * Get executionTestResultId
   * @return executionTestResultId
  **/
  @Schema(description = "")
  public Long getExecutionTestResultId() {
    return executionTestResultId;
  }

  public void setExecutionTestResultId(Long executionTestResultId) {
    this.executionTestResultId = executionTestResultId;
  }

  public TestResultAssertionFailedResource executionTestResultResource(ExecutionTestResultResource executionTestResultResource) {
    this.executionTestResultResource = executionTestResultResource;
    return this;
  }

   /**
   * Get executionTestResultResource
   * @return executionTestResultResource
  **/
  @Schema(description = "")
  public ExecutionTestResultResource getExecutionTestResultResource() {
    return executionTestResultResource;
  }

  public void setExecutionTestResultResource(ExecutionTestResultResource executionTestResultResource) {
    this.executionTestResultResource = executionTestResultResource;
  }

  public TestResultAssertionFailedResource stacktrace(String stacktrace) {
    this.stacktrace = stacktrace;
    return this;
  }

   /**
   * Get stacktrace
   * @return stacktrace
  **/
  @Schema(description = "")
  public String getStacktrace() {
    return stacktrace;
  }

  public void setStacktrace(String stacktrace) {
    this.stacktrace = stacktrace;
  }

  public TestResultAssertionFailedResource message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  @Schema(description = "")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public TestResultAssertionFailedResource logTime(String logTime) {
    this.logTime = logTime;
    return this;
  }

   /**
   * Get logTime
   * @return logTime
  **/
  @Schema(description = "")
  public String getLogTime() {
    return logTime;
  }

  public void setLogTime(String logTime) {
    this.logTime = logTime;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TestResultAssertionFailedResource testResultAssertionFailedResource = (TestResultAssertionFailedResource) o;
    return Objects.equals(this.id, testResultAssertionFailedResource.id) &&
        Objects.equals(this.executionTestResultId, testResultAssertionFailedResource.executionTestResultId) &&
        Objects.equals(this.executionTestResultResource, testResultAssertionFailedResource.executionTestResultResource) &&
        Objects.equals(this.stacktrace, testResultAssertionFailedResource.stacktrace) &&
        Objects.equals(this.message, testResultAssertionFailedResource.message) &&
        Objects.equals(this.logTime, testResultAssertionFailedResource.logTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, executionTestResultId, executionTestResultResource, stacktrace, message, logTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TestResultAssertionFailedResource {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    executionTestResultId: ").append(toIndentedString(executionTestResultId)).append("\n");
    sb.append("    executionTestResultResource: ").append(toIndentedString(executionTestResultResource)).append("\n");
    sb.append("    stacktrace: ").append(toIndentedString(stacktrace)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    logTime: ").append(toIndentedString(logTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
