/*
 * Katalon TestOps API reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.katalon.testops.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * AgentResource
 */
@JsonPropertyOrder({
  AgentResource.JSON_PROPERTY_ID,
  AgentResource.JSON_PROPERTY_NAME,
  AgentResource.JSON_PROPERTY_IP,
  AgentResource.JSON_PROPERTY_UUID,
  AgentResource.JSON_PROPERTY_LAST_PING,
  AgentResource.JSON_PROPERTY_OS,
  AgentResource.JSON_PROPERTY_TEAM_ID,
  AgentResource.JSON_PROPERTY_HOSTNAME,
  AgentResource.JSON_PROPERTY_ACTIVE,
  AgentResource.JSON_PROPERTY_THRESHOLD,
  AgentResource.JSON_PROPERTY_NUM_EXECUTING_JOBS,
  AgentResource.JSON_PROPERTY_NUM_ASSIGNED_JOBS,
  AgentResource.JSON_PROPERTY_AGENT_VERSION,
  AgentResource.JSON_PROPERTY_DELETED
})
@JsonTypeName("AgentResource")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class AgentResource implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_ID = "id";
  private Long id;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_IP = "ip";
  private String ip;

  public static final String JSON_PROPERTY_UUID = "uuid";
  private String uuid;

  public static final String JSON_PROPERTY_LAST_PING = "lastPing";
  private OffsetDateTime lastPing;

  public static final String JSON_PROPERTY_OS = "os";
  private String os;

  public static final String JSON_PROPERTY_TEAM_ID = "teamId";
  private Long teamId;

  public static final String JSON_PROPERTY_HOSTNAME = "hostname";
  private String hostname;

  public static final String JSON_PROPERTY_ACTIVE = "active";
  private Boolean active;

  public static final String JSON_PROPERTY_THRESHOLD = "threshold";
  private Long threshold;

  public static final String JSON_PROPERTY_NUM_EXECUTING_JOBS = "numExecutingJobs";
  private Integer numExecutingJobs;

  public static final String JSON_PROPERTY_NUM_ASSIGNED_JOBS = "numAssignedJobs";
  private Integer numAssignedJobs;

  public static final String JSON_PROPERTY_AGENT_VERSION = "agentVersion";
  private String agentVersion;

  public static final String JSON_PROPERTY_DELETED = "deleted";
  private Boolean deleted;


  public AgentResource id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  public void setId(Long id) {
    this.id = id;
  }


  public AgentResource name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public AgentResource ip(String ip) {
    
    this.ip = ip;
    return this;
  }

   /**
   * Get ip
   * @return ip
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_IP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIp() {
    return ip;
  }


  public void setIp(String ip) {
    this.ip = ip;
  }


  public AgentResource uuid(String uuid) {
    
    this.uuid = uuid;
    return this;
  }

   /**
   * Get uuid
   * @return uuid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_UUID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUuid() {
    return uuid;
  }


  public void setUuid(String uuid) {
    this.uuid = uuid;
  }


  public AgentResource lastPing(OffsetDateTime lastPing) {
    
    this.lastPing = lastPing;
    return this;
  }

   /**
   * Get lastPing
   * @return lastPing
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LAST_PING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getLastPing() {
    return lastPing;
  }


  public void setLastPing(OffsetDateTime lastPing) {
    this.lastPing = lastPing;
  }


  public AgentResource os(String os) {
    
    this.os = os;
    return this;
  }

   /**
   * Get os
   * @return os
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_OS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOs() {
    return os;
  }


  public void setOs(String os) {
    this.os = os;
  }


  public AgentResource teamId(Long teamId) {
    
    this.teamId = teamId;
    return this;
  }

   /**
   * Get teamId
   * @return teamId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TEAM_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTeamId() {
    return teamId;
  }


  public void setTeamId(Long teamId) {
    this.teamId = teamId;
  }


  public AgentResource hostname(String hostname) {
    
    this.hostname = hostname;
    return this;
  }

   /**
   * Get hostname
   * @return hostname
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_HOSTNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getHostname() {
    return hostname;
  }


  public void setHostname(String hostname) {
    this.hostname = hostname;
  }


  public AgentResource active(Boolean active) {
    
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ACTIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getActive() {
    return active;
  }


  public void setActive(Boolean active) {
    this.active = active;
  }


  public AgentResource threshold(Long threshold) {
    
    this.threshold = threshold;
    return this;
  }

   /**
   * Get threshold
   * @return threshold
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_THRESHOLD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getThreshold() {
    return threshold;
  }


  public void setThreshold(Long threshold) {
    this.threshold = threshold;
  }


  public AgentResource numExecutingJobs(Integer numExecutingJobs) {
    
    this.numExecutingJobs = numExecutingJobs;
    return this;
  }

   /**
   * Get numExecutingJobs
   * @return numExecutingJobs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NUM_EXECUTING_JOBS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getNumExecutingJobs() {
    return numExecutingJobs;
  }


  public void setNumExecutingJobs(Integer numExecutingJobs) {
    this.numExecutingJobs = numExecutingJobs;
  }


  public AgentResource numAssignedJobs(Integer numAssignedJobs) {
    
    this.numAssignedJobs = numAssignedJobs;
    return this;
  }

   /**
   * Get numAssignedJobs
   * @return numAssignedJobs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NUM_ASSIGNED_JOBS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getNumAssignedJobs() {
    return numAssignedJobs;
  }


  public void setNumAssignedJobs(Integer numAssignedJobs) {
    this.numAssignedJobs = numAssignedJobs;
  }


  public AgentResource agentVersion(String agentVersion) {
    
    this.agentVersion = agentVersion;
    return this;
  }

   /**
   * Get agentVersion
   * @return agentVersion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AGENT_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAgentVersion() {
    return agentVersion;
  }


  public void setAgentVersion(String agentVersion) {
    this.agentVersion = agentVersion;
  }


  public AgentResource deleted(Boolean deleted) {
    
    this.deleted = deleted;
    return this;
  }

   /**
   * Get deleted
   * @return deleted
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDeleted() {
    return deleted;
  }


  public void setDeleted(Boolean deleted) {
    this.deleted = deleted;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AgentResource agentResource = (AgentResource) o;
    return Objects.equals(this.id, agentResource.id) &&
        Objects.equals(this.name, agentResource.name) &&
        Objects.equals(this.ip, agentResource.ip) &&
        Objects.equals(this.uuid, agentResource.uuid) &&
        Objects.equals(this.lastPing, agentResource.lastPing) &&
        Objects.equals(this.os, agentResource.os) &&
        Objects.equals(this.teamId, agentResource.teamId) &&
        Objects.equals(this.hostname, agentResource.hostname) &&
        Objects.equals(this.active, agentResource.active) &&
        Objects.equals(this.threshold, agentResource.threshold) &&
        Objects.equals(this.numExecutingJobs, agentResource.numExecutingJobs) &&
        Objects.equals(this.numAssignedJobs, agentResource.numAssignedJobs) &&
        Objects.equals(this.agentVersion, agentResource.agentVersion) &&
        Objects.equals(this.deleted, agentResource.deleted);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, ip, uuid, lastPing, os, teamId, hostname, active, threshold, numExecutingJobs, numAssignedJobs, agentVersion, deleted);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AgentResource {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    ip: ").append(toIndentedString(ip)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    lastPing: ").append(toIndentedString(lastPing)).append("\n");
    sb.append("    os: ").append(toIndentedString(os)).append("\n");
    sb.append("    teamId: ").append(toIndentedString(teamId)).append("\n");
    sb.append("    hostname: ").append(toIndentedString(hostname)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    threshold: ").append(toIndentedString(threshold)).append("\n");
    sb.append("    numExecutingJobs: ").append(toIndentedString(numExecutingJobs)).append("\n");
    sb.append("    numAssignedJobs: ").append(toIndentedString(numAssignedJobs)).append("\n");
    sb.append("    agentVersion: ").append(toIndentedString(agentVersion)).append("\n");
    sb.append("    deleted: ").append(toIndentedString(deleted)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

