/*
 * Katalon TestOps API reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.katalon.testops.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.katalon.testops.api.model.BuildLog;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * BuildInfo
 */
@JsonPropertyOrder({
  BuildInfo.JSON_PROPERTY_BUILD_NUM,
  BuildInfo.JSON_PROPERTY_JOB_ID,
  BuildInfo.JSON_PROPERTY_BUILD_TIME_MILLIS,
  BuildInfo.JSON_PROPERTY_STATUS,
  BuildInfo.JSON_PROPERTY_USAGE_QUEUED_AT,
  BuildInfo.JSON_PROPERTY_START_TIME,
  BuildInfo.JSON_PROPERTY_STOP_TIME,
  BuildInfo.JSON_PROPERTY_STEPS
})
@JsonTypeName("BuildInfo")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class BuildInfo implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_BUILD_NUM = "build_num";
  private Long buildNum;

  public static final String JSON_PROPERTY_JOB_ID = "job_id";
  private Long jobId;

  public static final String JSON_PROPERTY_BUILD_TIME_MILLIS = "build_time_millis";
  private Long buildTimeMillis;

  public static final String JSON_PROPERTY_STATUS = "status";
  private String status;

  public static final String JSON_PROPERTY_USAGE_QUEUED_AT = "usage_queued_at";
  private OffsetDateTime usageQueuedAt;

  public static final String JSON_PROPERTY_START_TIME = "start_time";
  private OffsetDateTime startTime;

  public static final String JSON_PROPERTY_STOP_TIME = "stop_time";
  private OffsetDateTime stopTime;

  public static final String JSON_PROPERTY_STEPS = "steps";
  private List<BuildLog> steps = null;


  public BuildInfo buildNum(Long buildNum) {
    
    this.buildNum = buildNum;
    return this;
  }

   /**
   * Get buildNum
   * @return buildNum
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_BUILD_NUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getBuildNum() {
    return buildNum;
  }


  public void setBuildNum(Long buildNum) {
    this.buildNum = buildNum;
  }


  public BuildInfo jobId(Long jobId) {
    
    this.jobId = jobId;
    return this;
  }

   /**
   * Get jobId
   * @return jobId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_JOB_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getJobId() {
    return jobId;
  }


  public void setJobId(Long jobId) {
    this.jobId = jobId;
  }


  public BuildInfo buildTimeMillis(Long buildTimeMillis) {
    
    this.buildTimeMillis = buildTimeMillis;
    return this;
  }

   /**
   * Get buildTimeMillis
   * @return buildTimeMillis
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_BUILD_TIME_MILLIS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getBuildTimeMillis() {
    return buildTimeMillis;
  }


  public void setBuildTimeMillis(Long buildTimeMillis) {
    this.buildTimeMillis = buildTimeMillis;
  }


  public BuildInfo status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStatus() {
    return status;
  }


  public void setStatus(String status) {
    this.status = status;
  }


  public BuildInfo usageQueuedAt(OffsetDateTime usageQueuedAt) {
    
    this.usageQueuedAt = usageQueuedAt;
    return this;
  }

   /**
   * Get usageQueuedAt
   * @return usageQueuedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_USAGE_QUEUED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getUsageQueuedAt() {
    return usageQueuedAt;
  }


  public void setUsageQueuedAt(OffsetDateTime usageQueuedAt) {
    this.usageQueuedAt = usageQueuedAt;
  }


  public BuildInfo startTime(OffsetDateTime startTime) {
    
    this.startTime = startTime;
    return this;
  }

   /**
   * Get startTime
   * @return startTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_START_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getStartTime() {
    return startTime;
  }


  public void setStartTime(OffsetDateTime startTime) {
    this.startTime = startTime;
  }


  public BuildInfo stopTime(OffsetDateTime stopTime) {
    
    this.stopTime = stopTime;
    return this;
  }

   /**
   * Get stopTime
   * @return stopTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STOP_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getStopTime() {
    return stopTime;
  }


  public void setStopTime(OffsetDateTime stopTime) {
    this.stopTime = stopTime;
  }


  public BuildInfo steps(List<BuildLog> steps) {
    
    this.steps = steps;
    return this;
  }

  public BuildInfo addStepsItem(BuildLog stepsItem) {
    if (this.steps == null) {
      this.steps = new ArrayList<>();
    }
    this.steps.add(stepsItem);
    return this;
  }

   /**
   * Get steps
   * @return steps
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STEPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<BuildLog> getSteps() {
    return steps;
  }


  public void setSteps(List<BuildLog> steps) {
    this.steps = steps;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BuildInfo buildInfo = (BuildInfo) o;
    return Objects.equals(this.buildNum, buildInfo.buildNum) &&
        Objects.equals(this.jobId, buildInfo.jobId) &&
        Objects.equals(this.buildTimeMillis, buildInfo.buildTimeMillis) &&
        Objects.equals(this.status, buildInfo.status) &&
        Objects.equals(this.usageQueuedAt, buildInfo.usageQueuedAt) &&
        Objects.equals(this.startTime, buildInfo.startTime) &&
        Objects.equals(this.stopTime, buildInfo.stopTime) &&
        Objects.equals(this.steps, buildInfo.steps);
  }

  @Override
  public int hashCode() {
    return Objects.hash(buildNum, jobId, buildTimeMillis, status, usageQueuedAt, startTime, stopTime, steps);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BuildInfo {\n");
    sb.append("    buildNum: ").append(toIndentedString(buildNum)).append("\n");
    sb.append("    jobId: ").append(toIndentedString(jobId)).append("\n");
    sb.append("    buildTimeMillis: ").append(toIndentedString(buildTimeMillis)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    usageQueuedAt: ").append(toIndentedString(usageQueuedAt)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    stopTime: ").append(toIndentedString(stopTime)).append("\n");
    sb.append("    steps: ").append(toIndentedString(steps)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

