/*
 * Katalon TestOps API reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.katalon.testops.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * CircleCIProject
 */
@JsonPropertyOrder({
  CircleCIProject.JSON_PROPERTY_USERNAME,
  CircleCIProject.JSON_PROPERTY_BRANCHES,
  CircleCIProject.JSON_PROPERTY_REPONAME,
  CircleCIProject.JSON_PROPERTY_VCS_URL,
  CircleCIProject.JSON_PROPERTY_VCS_TYPE
})
@JsonTypeName("CircleCIProject")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class CircleCIProject implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_USERNAME = "username";
  private String username;

  public static final String JSON_PROPERTY_BRANCHES = "branches";
  private Map<String, Object> branches = null;

  public static final String JSON_PROPERTY_REPONAME = "reponame";
  private String reponame;

  public static final String JSON_PROPERTY_VCS_URL = "vcs_url";
  private String vcsUrl;

  public static final String JSON_PROPERTY_VCS_TYPE = "vcs_type";
  private String vcsType;


  public CircleCIProject username(String username) {
    
    this.username = username;
    return this;
  }

   /**
   * Get username
   * @return username
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_USERNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUsername() {
    return username;
  }


  public void setUsername(String username) {
    this.username = username;
  }


  public CircleCIProject branches(Map<String, Object> branches) {
    
    this.branches = branches;
    return this;
  }

  public CircleCIProject putBranchesItem(String key, Object branchesItem) {
    if (this.branches == null) {
      this.branches = new HashMap<>();
    }
    this.branches.put(key, branchesItem);
    return this;
  }

   /**
   * Get branches
   * @return branches
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_BRANCHES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, Object> getBranches() {
    return branches;
  }


  public void setBranches(Map<String, Object> branches) {
    this.branches = branches;
  }


  public CircleCIProject reponame(String reponame) {
    
    this.reponame = reponame;
    return this;
  }

   /**
   * Get reponame
   * @return reponame
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_REPONAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReponame() {
    return reponame;
  }


  public void setReponame(String reponame) {
    this.reponame = reponame;
  }


  public CircleCIProject vcsUrl(String vcsUrl) {
    
    this.vcsUrl = vcsUrl;
    return this;
  }

   /**
   * Get vcsUrl
   * @return vcsUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_VCS_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVcsUrl() {
    return vcsUrl;
  }


  public void setVcsUrl(String vcsUrl) {
    this.vcsUrl = vcsUrl;
  }


  public CircleCIProject vcsType(String vcsType) {
    
    this.vcsType = vcsType;
    return this;
  }

   /**
   * Get vcsType
   * @return vcsType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_VCS_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVcsType() {
    return vcsType;
  }


  public void setVcsType(String vcsType) {
    this.vcsType = vcsType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CircleCIProject circleCIProject = (CircleCIProject) o;
    return Objects.equals(this.username, circleCIProject.username) &&
        Objects.equals(this.branches, circleCIProject.branches) &&
        Objects.equals(this.reponame, circleCIProject.reponame) &&
        Objects.equals(this.vcsUrl, circleCIProject.vcsUrl) &&
        Objects.equals(this.vcsType, circleCIProject.vcsType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(username, branches, reponame, vcsUrl, vcsType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CircleCIProject {\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    branches: ").append(toIndentedString(branches)).append("\n");
    sb.append("    reponame: ").append(toIndentedString(reponame)).append("\n");
    sb.append("    vcsUrl: ").append(toIndentedString(vcsUrl)).append("\n");
    sb.append("    vcsType: ").append(toIndentedString(vcsType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

