/*
 * Katalon TestOps API reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.katalon.testops.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * ExecutionTestCaseResource
 */
@JsonPropertyOrder({
  ExecutionTestCaseResource.JSON_PROPERTY_STATUS,
  ExecutionTestCaseResource.JSON_PROPERTY_START_TIME,
  ExecutionTestCaseResource.JSON_PROPERTY_END_TIME,
  ExecutionTestCaseResource.JSON_PROPERTY_DURATION,
  ExecutionTestCaseResource.JSON_PROPERTY_ELAPSED_DURATION,
  ExecutionTestCaseResource.JSON_PROPERTY_TOTAL_TESTS,
  ExecutionTestCaseResource.JSON_PROPERTY_TOTAL_PASSED_TESTS,
  ExecutionTestCaseResource.JSON_PROPERTY_TOTAL_FAILED_TESTS,
  ExecutionTestCaseResource.JSON_PROPERTY_TOTAL_ERROR_TESTS,
  ExecutionTestCaseResource.JSON_PROPERTY_TOTAL_INCOMPLETE_TESTS,
  ExecutionTestCaseResource.JSON_PROPERTY_TOTAL_DIFF_TESTS,
  ExecutionTestCaseResource.JSON_PROPERTY_TOTAL_DIFF_PASSED_TESTS,
  ExecutionTestCaseResource.JSON_PROPERTY_TOTAL_DIFF_FAILED_TESTS,
  ExecutionTestCaseResource.JSON_PROPERTY_TOTAL_DIFF_ERROR_TESTS,
  ExecutionTestCaseResource.JSON_PROPERTY_TOTAL_DIFF_INCOMPLETE_TESTS,
  ExecutionTestCaseResource.JSON_PROPERTY_EXECUTION_ID,
  ExecutionTestCaseResource.JSON_PROPERTY_EXECUTION_ORDER,
  ExecutionTestCaseResource.JSON_PROPERTY_TEST_CASE_ID,
  ExecutionTestCaseResource.JSON_PROPERTY_PROJECT_ID
})
@JsonTypeName("ExecutionTestCaseResource")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ExecutionTestCaseResource implements Serializable {
  private static final long serialVersionUID = 1L;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    PASSED("PASSED"),
    
    FAILED("FAILED"),
    
    ERROR("ERROR"),
    
    INCOMPLETE("INCOMPLETE"),
    
    RUNNING("RUNNING"),
    
    SKIPPED("SKIPPED"),
    
    NOT_RUN("NOT_RUN");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  private StatusEnum status;

  public static final String JSON_PROPERTY_START_TIME = "startTime";
  private OffsetDateTime startTime;

  public static final String JSON_PROPERTY_END_TIME = "endTime";
  private OffsetDateTime endTime;

  public static final String JSON_PROPERTY_DURATION = "duration";
  private Long duration;

  public static final String JSON_PROPERTY_ELAPSED_DURATION = "elapsedDuration";
  private Long elapsedDuration;

  public static final String JSON_PROPERTY_TOTAL_TESTS = "totalTests";
  private Long totalTests;

  public static final String JSON_PROPERTY_TOTAL_PASSED_TESTS = "totalPassedTests";
  private Long totalPassedTests;

  public static final String JSON_PROPERTY_TOTAL_FAILED_TESTS = "totalFailedTests";
  private Long totalFailedTests;

  public static final String JSON_PROPERTY_TOTAL_ERROR_TESTS = "totalErrorTests";
  private Long totalErrorTests;

  public static final String JSON_PROPERTY_TOTAL_INCOMPLETE_TESTS = "totalIncompleteTests";
  private Long totalIncompleteTests;

  public static final String JSON_PROPERTY_TOTAL_DIFF_TESTS = "totalDiffTests";
  private Long totalDiffTests;

  public static final String JSON_PROPERTY_TOTAL_DIFF_PASSED_TESTS = "totalDiffPassedTests";
  private Long totalDiffPassedTests;

  public static final String JSON_PROPERTY_TOTAL_DIFF_FAILED_TESTS = "totalDiffFailedTests";
  private Long totalDiffFailedTests;

  public static final String JSON_PROPERTY_TOTAL_DIFF_ERROR_TESTS = "totalDiffErrorTests";
  private Long totalDiffErrorTests;

  public static final String JSON_PROPERTY_TOTAL_DIFF_INCOMPLETE_TESTS = "totalDiffIncompleteTests";
  private Long totalDiffIncompleteTests;

  public static final String JSON_PROPERTY_EXECUTION_ID = "executionId";
  private Long executionId;

  public static final String JSON_PROPERTY_EXECUTION_ORDER = "executionOrder";
  private Long executionOrder;

  public static final String JSON_PROPERTY_TEST_CASE_ID = "testCaseId";
  private Long testCaseId;

  public static final String JSON_PROPERTY_PROJECT_ID = "projectId";
  private Long projectId;


  public ExecutionTestCaseResource status(StatusEnum status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StatusEnum getStatus() {
    return status;
  }


  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  public ExecutionTestCaseResource startTime(OffsetDateTime startTime) {
    
    this.startTime = startTime;
    return this;
  }

   /**
   * Get startTime
   * @return startTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_START_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getStartTime() {
    return startTime;
  }


  public void setStartTime(OffsetDateTime startTime) {
    this.startTime = startTime;
  }


  public ExecutionTestCaseResource endTime(OffsetDateTime endTime) {
    
    this.endTime = endTime;
    return this;
  }

   /**
   * Get endTime
   * @return endTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_END_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getEndTime() {
    return endTime;
  }


  public void setEndTime(OffsetDateTime endTime) {
    this.endTime = endTime;
  }


  public ExecutionTestCaseResource duration(Long duration) {
    
    this.duration = duration;
    return this;
  }

   /**
   * Get duration
   * @return duration
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getDuration() {
    return duration;
  }


  public void setDuration(Long duration) {
    this.duration = duration;
  }


  public ExecutionTestCaseResource elapsedDuration(Long elapsedDuration) {
    
    this.elapsedDuration = elapsedDuration;
    return this;
  }

   /**
   * Get elapsedDuration
   * @return elapsedDuration
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ELAPSED_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getElapsedDuration() {
    return elapsedDuration;
  }


  public void setElapsedDuration(Long elapsedDuration) {
    this.elapsedDuration = elapsedDuration;
  }


  public ExecutionTestCaseResource totalTests(Long totalTests) {
    
    this.totalTests = totalTests;
    return this;
  }

   /**
   * Get totalTests
   * @return totalTests
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TOTAL_TESTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTotalTests() {
    return totalTests;
  }


  public void setTotalTests(Long totalTests) {
    this.totalTests = totalTests;
  }


  public ExecutionTestCaseResource totalPassedTests(Long totalPassedTests) {
    
    this.totalPassedTests = totalPassedTests;
    return this;
  }

   /**
   * Get totalPassedTests
   * @return totalPassedTests
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TOTAL_PASSED_TESTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTotalPassedTests() {
    return totalPassedTests;
  }


  public void setTotalPassedTests(Long totalPassedTests) {
    this.totalPassedTests = totalPassedTests;
  }


  public ExecutionTestCaseResource totalFailedTests(Long totalFailedTests) {
    
    this.totalFailedTests = totalFailedTests;
    return this;
  }

   /**
   * Get totalFailedTests
   * @return totalFailedTests
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TOTAL_FAILED_TESTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTotalFailedTests() {
    return totalFailedTests;
  }


  public void setTotalFailedTests(Long totalFailedTests) {
    this.totalFailedTests = totalFailedTests;
  }


  public ExecutionTestCaseResource totalErrorTests(Long totalErrorTests) {
    
    this.totalErrorTests = totalErrorTests;
    return this;
  }

   /**
   * Get totalErrorTests
   * @return totalErrorTests
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TOTAL_ERROR_TESTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTotalErrorTests() {
    return totalErrorTests;
  }


  public void setTotalErrorTests(Long totalErrorTests) {
    this.totalErrorTests = totalErrorTests;
  }


  public ExecutionTestCaseResource totalIncompleteTests(Long totalIncompleteTests) {
    
    this.totalIncompleteTests = totalIncompleteTests;
    return this;
  }

   /**
   * Get totalIncompleteTests
   * @return totalIncompleteTests
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TOTAL_INCOMPLETE_TESTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTotalIncompleteTests() {
    return totalIncompleteTests;
  }


  public void setTotalIncompleteTests(Long totalIncompleteTests) {
    this.totalIncompleteTests = totalIncompleteTests;
  }


  public ExecutionTestCaseResource totalDiffTests(Long totalDiffTests) {
    
    this.totalDiffTests = totalDiffTests;
    return this;
  }

   /**
   * Get totalDiffTests
   * @return totalDiffTests
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TOTAL_DIFF_TESTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTotalDiffTests() {
    return totalDiffTests;
  }


  public void setTotalDiffTests(Long totalDiffTests) {
    this.totalDiffTests = totalDiffTests;
  }


  public ExecutionTestCaseResource totalDiffPassedTests(Long totalDiffPassedTests) {
    
    this.totalDiffPassedTests = totalDiffPassedTests;
    return this;
  }

   /**
   * Get totalDiffPassedTests
   * @return totalDiffPassedTests
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TOTAL_DIFF_PASSED_TESTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTotalDiffPassedTests() {
    return totalDiffPassedTests;
  }


  public void setTotalDiffPassedTests(Long totalDiffPassedTests) {
    this.totalDiffPassedTests = totalDiffPassedTests;
  }


  public ExecutionTestCaseResource totalDiffFailedTests(Long totalDiffFailedTests) {
    
    this.totalDiffFailedTests = totalDiffFailedTests;
    return this;
  }

   /**
   * Get totalDiffFailedTests
   * @return totalDiffFailedTests
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TOTAL_DIFF_FAILED_TESTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTotalDiffFailedTests() {
    return totalDiffFailedTests;
  }


  public void setTotalDiffFailedTests(Long totalDiffFailedTests) {
    this.totalDiffFailedTests = totalDiffFailedTests;
  }


  public ExecutionTestCaseResource totalDiffErrorTests(Long totalDiffErrorTests) {
    
    this.totalDiffErrorTests = totalDiffErrorTests;
    return this;
  }

   /**
   * Get totalDiffErrorTests
   * @return totalDiffErrorTests
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TOTAL_DIFF_ERROR_TESTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTotalDiffErrorTests() {
    return totalDiffErrorTests;
  }


  public void setTotalDiffErrorTests(Long totalDiffErrorTests) {
    this.totalDiffErrorTests = totalDiffErrorTests;
  }


  public ExecutionTestCaseResource totalDiffIncompleteTests(Long totalDiffIncompleteTests) {
    
    this.totalDiffIncompleteTests = totalDiffIncompleteTests;
    return this;
  }

   /**
   * Get totalDiffIncompleteTests
   * @return totalDiffIncompleteTests
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TOTAL_DIFF_INCOMPLETE_TESTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTotalDiffIncompleteTests() {
    return totalDiffIncompleteTests;
  }


  public void setTotalDiffIncompleteTests(Long totalDiffIncompleteTests) {
    this.totalDiffIncompleteTests = totalDiffIncompleteTests;
  }


  public ExecutionTestCaseResource executionId(Long executionId) {
    
    this.executionId = executionId;
    return this;
  }

   /**
   * Get executionId
   * @return executionId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_EXECUTION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getExecutionId() {
    return executionId;
  }


  public void setExecutionId(Long executionId) {
    this.executionId = executionId;
  }


  public ExecutionTestCaseResource executionOrder(Long executionOrder) {
    
    this.executionOrder = executionOrder;
    return this;
  }

   /**
   * Get executionOrder
   * @return executionOrder
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_EXECUTION_ORDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getExecutionOrder() {
    return executionOrder;
  }


  public void setExecutionOrder(Long executionOrder) {
    this.executionOrder = executionOrder;
  }


  public ExecutionTestCaseResource testCaseId(Long testCaseId) {
    
    this.testCaseId = testCaseId;
    return this;
  }

   /**
   * Get testCaseId
   * @return testCaseId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TEST_CASE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTestCaseId() {
    return testCaseId;
  }


  public void setTestCaseId(Long testCaseId) {
    this.testCaseId = testCaseId;
  }


  public ExecutionTestCaseResource projectId(Long projectId) {
    
    this.projectId = projectId;
    return this;
  }

   /**
   * Get projectId
   * @return projectId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PROJECT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getProjectId() {
    return projectId;
  }


  public void setProjectId(Long projectId) {
    this.projectId = projectId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExecutionTestCaseResource executionTestCaseResource = (ExecutionTestCaseResource) o;
    return Objects.equals(this.status, executionTestCaseResource.status) &&
        Objects.equals(this.startTime, executionTestCaseResource.startTime) &&
        Objects.equals(this.endTime, executionTestCaseResource.endTime) &&
        Objects.equals(this.duration, executionTestCaseResource.duration) &&
        Objects.equals(this.elapsedDuration, executionTestCaseResource.elapsedDuration) &&
        Objects.equals(this.totalTests, executionTestCaseResource.totalTests) &&
        Objects.equals(this.totalPassedTests, executionTestCaseResource.totalPassedTests) &&
        Objects.equals(this.totalFailedTests, executionTestCaseResource.totalFailedTests) &&
        Objects.equals(this.totalErrorTests, executionTestCaseResource.totalErrorTests) &&
        Objects.equals(this.totalIncompleteTests, executionTestCaseResource.totalIncompleteTests) &&
        Objects.equals(this.totalDiffTests, executionTestCaseResource.totalDiffTests) &&
        Objects.equals(this.totalDiffPassedTests, executionTestCaseResource.totalDiffPassedTests) &&
        Objects.equals(this.totalDiffFailedTests, executionTestCaseResource.totalDiffFailedTests) &&
        Objects.equals(this.totalDiffErrorTests, executionTestCaseResource.totalDiffErrorTests) &&
        Objects.equals(this.totalDiffIncompleteTests, executionTestCaseResource.totalDiffIncompleteTests) &&
        Objects.equals(this.executionId, executionTestCaseResource.executionId) &&
        Objects.equals(this.executionOrder, executionTestCaseResource.executionOrder) &&
        Objects.equals(this.testCaseId, executionTestCaseResource.testCaseId) &&
        Objects.equals(this.projectId, executionTestCaseResource.projectId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, startTime, endTime, duration, elapsedDuration, totalTests, totalPassedTests, totalFailedTests, totalErrorTests, totalIncompleteTests, totalDiffTests, totalDiffPassedTests, totalDiffFailedTests, totalDiffErrorTests, totalDiffIncompleteTests, executionId, executionOrder, testCaseId, projectId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExecutionTestCaseResource {\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    elapsedDuration: ").append(toIndentedString(elapsedDuration)).append("\n");
    sb.append("    totalTests: ").append(toIndentedString(totalTests)).append("\n");
    sb.append("    totalPassedTests: ").append(toIndentedString(totalPassedTests)).append("\n");
    sb.append("    totalFailedTests: ").append(toIndentedString(totalFailedTests)).append("\n");
    sb.append("    totalErrorTests: ").append(toIndentedString(totalErrorTests)).append("\n");
    sb.append("    totalIncompleteTests: ").append(toIndentedString(totalIncompleteTests)).append("\n");
    sb.append("    totalDiffTests: ").append(toIndentedString(totalDiffTests)).append("\n");
    sb.append("    totalDiffPassedTests: ").append(toIndentedString(totalDiffPassedTests)).append("\n");
    sb.append("    totalDiffFailedTests: ").append(toIndentedString(totalDiffFailedTests)).append("\n");
    sb.append("    totalDiffErrorTests: ").append(toIndentedString(totalDiffErrorTests)).append("\n");
    sb.append("    totalDiffIncompleteTests: ").append(toIndentedString(totalDiffIncompleteTests)).append("\n");
    sb.append("    executionId: ").append(toIndentedString(executionId)).append("\n");
    sb.append("    executionOrder: ").append(toIndentedString(executionOrder)).append("\n");
    sb.append("    testCaseId: ").append(toIndentedString(testCaseId)).append("\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

