/*
 * Katalon TestOps API reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.katalon.testops.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.katalon.testops.api.model.ExecutionTestSuiteResource;
import com.katalon.testops.api.model.JobResource;
import com.katalon.testops.api.model.ProjectResource;
import com.katalon.testops.api.model.ReleaseResource;
import com.katalon.testops.api.model.TestSuiteCollectionEntityResource;
import com.katalon.testops.api.model.UserResource;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * ExecutionResource
 */
@JsonPropertyOrder({
  ExecutionResource.JSON_PROPERTY_STATUS,
  ExecutionResource.JSON_PROPERTY_START_TIME,
  ExecutionResource.JSON_PROPERTY_END_TIME,
  ExecutionResource.JSON_PROPERTY_DURATION,
  ExecutionResource.JSON_PROPERTY_ELAPSED_DURATION,
  ExecutionResource.JSON_PROPERTY_TOTAL_TESTS,
  ExecutionResource.JSON_PROPERTY_TOTAL_PASSED_TESTS,
  ExecutionResource.JSON_PROPERTY_TOTAL_FAILED_TESTS,
  ExecutionResource.JSON_PROPERTY_TOTAL_ERROR_TESTS,
  ExecutionResource.JSON_PROPERTY_TOTAL_INCOMPLETE_TESTS,
  ExecutionResource.JSON_PROPERTY_TOTAL_DIFF_TESTS,
  ExecutionResource.JSON_PROPERTY_TOTAL_DIFF_PASSED_TESTS,
  ExecutionResource.JSON_PROPERTY_TOTAL_DIFF_FAILED_TESTS,
  ExecutionResource.JSON_PROPERTY_TOTAL_DIFF_ERROR_TESTS,
  ExecutionResource.JSON_PROPERTY_TOTAL_DIFF_INCOMPLETE_TESTS,
  ExecutionResource.JSON_PROPERTY_ID,
  ExecutionResource.JSON_PROPERTY_PROJECT_ID,
  ExecutionResource.JSON_PROPERTY_PROJECT,
  ExecutionResource.JSON_PROPERTY_BUILD_ID,
  ExecutionResource.JSON_PROPERTY_ORDER,
  ExecutionResource.JSON_PROPERTY_EXECUTION_STAGE,
  ExecutionResource.JSON_PROPERTY_WEB_URL,
  ExecutionResource.JSON_PROPERTY_TEST_SUITE_COLLECTIONS,
  ExecutionResource.JSON_PROPERTY_EXECUTION_TEST_SUITE_RESOURCES,
  ExecutionResource.JSON_PROPERTY_RELEASE,
  ExecutionResource.JSON_PROPERTY_HAS_COMMENT,
  ExecutionResource.JSON_PROPERTY_USER,
  ExecutionResource.JSON_PROPERTY_SESSION_ID,
  ExecutionResource.JSON_PROPERTY_BUILD_LABEL,
  ExecutionResource.JSON_PROPERTY_BUILD_URL,
  ExecutionResource.JSON_PROPERTY_TYPE,
  ExecutionResource.JSON_PROPERTY_JOBS
})
@JsonTypeName("ExecutionResource")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ExecutionResource implements Serializable {
  private static final long serialVersionUID = 1L;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    PASSED("PASSED"),
    
    FAILED("FAILED"),
    
    ERROR("ERROR"),
    
    INCOMPLETE("INCOMPLETE"),
    
    RUNNING("RUNNING"),
    
    SKIPPED("SKIPPED"),
    
    NOT_RUN("NOT_RUN");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  private StatusEnum status;

  public static final String JSON_PROPERTY_START_TIME = "startTime";
  private OffsetDateTime startTime;

  public static final String JSON_PROPERTY_END_TIME = "endTime";
  private OffsetDateTime endTime;

  public static final String JSON_PROPERTY_DURATION = "duration";
  private Long duration;

  public static final String JSON_PROPERTY_ELAPSED_DURATION = "elapsedDuration";
  private Long elapsedDuration;

  public static final String JSON_PROPERTY_TOTAL_TESTS = "totalTests";
  private Long totalTests;

  public static final String JSON_PROPERTY_TOTAL_PASSED_TESTS = "totalPassedTests";
  private Long totalPassedTests;

  public static final String JSON_PROPERTY_TOTAL_FAILED_TESTS = "totalFailedTests";
  private Long totalFailedTests;

  public static final String JSON_PROPERTY_TOTAL_ERROR_TESTS = "totalErrorTests";
  private Long totalErrorTests;

  public static final String JSON_PROPERTY_TOTAL_INCOMPLETE_TESTS = "totalIncompleteTests";
  private Long totalIncompleteTests;

  public static final String JSON_PROPERTY_TOTAL_DIFF_TESTS = "totalDiffTests";
  private Long totalDiffTests;

  public static final String JSON_PROPERTY_TOTAL_DIFF_PASSED_TESTS = "totalDiffPassedTests";
  private Long totalDiffPassedTests;

  public static final String JSON_PROPERTY_TOTAL_DIFF_FAILED_TESTS = "totalDiffFailedTests";
  private Long totalDiffFailedTests;

  public static final String JSON_PROPERTY_TOTAL_DIFF_ERROR_TESTS = "totalDiffErrorTests";
  private Long totalDiffErrorTests;

  public static final String JSON_PROPERTY_TOTAL_DIFF_INCOMPLETE_TESTS = "totalDiffIncompleteTests";
  private Long totalDiffIncompleteTests;

  public static final String JSON_PROPERTY_ID = "id";
  private Long id;

  public static final String JSON_PROPERTY_PROJECT_ID = "projectId";
  private Long projectId;

  public static final String JSON_PROPERTY_PROJECT = "project";
  private ProjectResource project;

  public static final String JSON_PROPERTY_BUILD_ID = "buildId";
  private Long buildId;

  public static final String JSON_PROPERTY_ORDER = "order";
  private Long order;

  /**
   * Gets or Sets executionStage
   */
  public enum ExecutionStageEnum {
    RUNNING("RUNNING"),
    
    COMPLETED("COMPLETED"),
    
    TERMINATE("TERMINATE"),
    
    ANALYZING("ANALYZING"),
    
    ANALYZED("ANALYZED"),
    
    IMPORTING("IMPORTING"),
    
    ERROR("ERROR");

    private String value;

    ExecutionStageEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ExecutionStageEnum fromValue(String value) {
      for (ExecutionStageEnum b : ExecutionStageEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_EXECUTION_STAGE = "executionStage";
  private ExecutionStageEnum executionStage;

  public static final String JSON_PROPERTY_WEB_URL = "webUrl";
  private String webUrl;

  public static final String JSON_PROPERTY_TEST_SUITE_COLLECTIONS = "testSuiteCollections";
  private List<TestSuiteCollectionEntityResource> testSuiteCollections = null;

  public static final String JSON_PROPERTY_EXECUTION_TEST_SUITE_RESOURCES = "executionTestSuiteResources";
  private List<ExecutionTestSuiteResource> executionTestSuiteResources = null;

  public static final String JSON_PROPERTY_RELEASE = "release";
  private ReleaseResource release;

  public static final String JSON_PROPERTY_HAS_COMMENT = "hasComment";
  private Boolean hasComment;

  public static final String JSON_PROPERTY_USER = "user";
  private UserResource user;

  public static final String JSON_PROPERTY_SESSION_ID = "sessionId";
  private String sessionId;

  public static final String JSON_PROPERTY_BUILD_LABEL = "buildLabel";
  private String buildLabel;

  public static final String JSON_PROPERTY_BUILD_URL = "buildUrl";
  private String buildUrl;

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    KATALON("KATALON"),
    
    BDD("BDD");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  private TypeEnum type;

  public static final String JSON_PROPERTY_JOBS = "jobs";
  private List<JobResource> jobs = null;


  public ExecutionResource status(StatusEnum status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StatusEnum getStatus() {
    return status;
  }


  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  public ExecutionResource startTime(OffsetDateTime startTime) {
    
    this.startTime = startTime;
    return this;
  }

   /**
   * Get startTime
   * @return startTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_START_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getStartTime() {
    return startTime;
  }


  public void setStartTime(OffsetDateTime startTime) {
    this.startTime = startTime;
  }


  public ExecutionResource endTime(OffsetDateTime endTime) {
    
    this.endTime = endTime;
    return this;
  }

   /**
   * Get endTime
   * @return endTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_END_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getEndTime() {
    return endTime;
  }


  public void setEndTime(OffsetDateTime endTime) {
    this.endTime = endTime;
  }


  public ExecutionResource duration(Long duration) {
    
    this.duration = duration;
    return this;
  }

   /**
   * Get duration
   * @return duration
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getDuration() {
    return duration;
  }


  public void setDuration(Long duration) {
    this.duration = duration;
  }


  public ExecutionResource elapsedDuration(Long elapsedDuration) {
    
    this.elapsedDuration = elapsedDuration;
    return this;
  }

   /**
   * Get elapsedDuration
   * @return elapsedDuration
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ELAPSED_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getElapsedDuration() {
    return elapsedDuration;
  }


  public void setElapsedDuration(Long elapsedDuration) {
    this.elapsedDuration = elapsedDuration;
  }


  public ExecutionResource totalTests(Long totalTests) {
    
    this.totalTests = totalTests;
    return this;
  }

   /**
   * Get totalTests
   * @return totalTests
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TOTAL_TESTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTotalTests() {
    return totalTests;
  }


  public void setTotalTests(Long totalTests) {
    this.totalTests = totalTests;
  }


  public ExecutionResource totalPassedTests(Long totalPassedTests) {
    
    this.totalPassedTests = totalPassedTests;
    return this;
  }

   /**
   * Get totalPassedTests
   * @return totalPassedTests
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TOTAL_PASSED_TESTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTotalPassedTests() {
    return totalPassedTests;
  }


  public void setTotalPassedTests(Long totalPassedTests) {
    this.totalPassedTests = totalPassedTests;
  }


  public ExecutionResource totalFailedTests(Long totalFailedTests) {
    
    this.totalFailedTests = totalFailedTests;
    return this;
  }

   /**
   * Get totalFailedTests
   * @return totalFailedTests
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TOTAL_FAILED_TESTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTotalFailedTests() {
    return totalFailedTests;
  }


  public void setTotalFailedTests(Long totalFailedTests) {
    this.totalFailedTests = totalFailedTests;
  }


  public ExecutionResource totalErrorTests(Long totalErrorTests) {
    
    this.totalErrorTests = totalErrorTests;
    return this;
  }

   /**
   * Get totalErrorTests
   * @return totalErrorTests
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TOTAL_ERROR_TESTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTotalErrorTests() {
    return totalErrorTests;
  }


  public void setTotalErrorTests(Long totalErrorTests) {
    this.totalErrorTests = totalErrorTests;
  }


  public ExecutionResource totalIncompleteTests(Long totalIncompleteTests) {
    
    this.totalIncompleteTests = totalIncompleteTests;
    return this;
  }

   /**
   * Get totalIncompleteTests
   * @return totalIncompleteTests
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TOTAL_INCOMPLETE_TESTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTotalIncompleteTests() {
    return totalIncompleteTests;
  }


  public void setTotalIncompleteTests(Long totalIncompleteTests) {
    this.totalIncompleteTests = totalIncompleteTests;
  }


  public ExecutionResource totalDiffTests(Long totalDiffTests) {
    
    this.totalDiffTests = totalDiffTests;
    return this;
  }

   /**
   * Get totalDiffTests
   * @return totalDiffTests
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TOTAL_DIFF_TESTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTotalDiffTests() {
    return totalDiffTests;
  }


  public void setTotalDiffTests(Long totalDiffTests) {
    this.totalDiffTests = totalDiffTests;
  }


  public ExecutionResource totalDiffPassedTests(Long totalDiffPassedTests) {
    
    this.totalDiffPassedTests = totalDiffPassedTests;
    return this;
  }

   /**
   * Get totalDiffPassedTests
   * @return totalDiffPassedTests
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TOTAL_DIFF_PASSED_TESTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTotalDiffPassedTests() {
    return totalDiffPassedTests;
  }


  public void setTotalDiffPassedTests(Long totalDiffPassedTests) {
    this.totalDiffPassedTests = totalDiffPassedTests;
  }


  public ExecutionResource totalDiffFailedTests(Long totalDiffFailedTests) {
    
    this.totalDiffFailedTests = totalDiffFailedTests;
    return this;
  }

   /**
   * Get totalDiffFailedTests
   * @return totalDiffFailedTests
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TOTAL_DIFF_FAILED_TESTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTotalDiffFailedTests() {
    return totalDiffFailedTests;
  }


  public void setTotalDiffFailedTests(Long totalDiffFailedTests) {
    this.totalDiffFailedTests = totalDiffFailedTests;
  }


  public ExecutionResource totalDiffErrorTests(Long totalDiffErrorTests) {
    
    this.totalDiffErrorTests = totalDiffErrorTests;
    return this;
  }

   /**
   * Get totalDiffErrorTests
   * @return totalDiffErrorTests
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TOTAL_DIFF_ERROR_TESTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTotalDiffErrorTests() {
    return totalDiffErrorTests;
  }


  public void setTotalDiffErrorTests(Long totalDiffErrorTests) {
    this.totalDiffErrorTests = totalDiffErrorTests;
  }


  public ExecutionResource totalDiffIncompleteTests(Long totalDiffIncompleteTests) {
    
    this.totalDiffIncompleteTests = totalDiffIncompleteTests;
    return this;
  }

   /**
   * Get totalDiffIncompleteTests
   * @return totalDiffIncompleteTests
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TOTAL_DIFF_INCOMPLETE_TESTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTotalDiffIncompleteTests() {
    return totalDiffIncompleteTests;
  }


  public void setTotalDiffIncompleteTests(Long totalDiffIncompleteTests) {
    this.totalDiffIncompleteTests = totalDiffIncompleteTests;
  }


  public ExecutionResource id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  public void setId(Long id) {
    this.id = id;
  }


  public ExecutionResource projectId(Long projectId) {
    
    this.projectId = projectId;
    return this;
  }

   /**
   * Get projectId
   * @return projectId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PROJECT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getProjectId() {
    return projectId;
  }


  public void setProjectId(Long projectId) {
    this.projectId = projectId;
  }


  public ExecutionResource project(ProjectResource project) {
    
    this.project = project;
    return this;
  }

   /**
   * Get project
   * @return project
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PROJECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ProjectResource getProject() {
    return project;
  }


  public void setProject(ProjectResource project) {
    this.project = project;
  }


  public ExecutionResource buildId(Long buildId) {
    
    this.buildId = buildId;
    return this;
  }

   /**
   * Get buildId
   * @return buildId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_BUILD_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getBuildId() {
    return buildId;
  }


  public void setBuildId(Long buildId) {
    this.buildId = buildId;
  }


  public ExecutionResource order(Long order) {
    
    this.order = order;
    return this;
  }

   /**
   * Get order
   * @return order
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ORDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getOrder() {
    return order;
  }


  public void setOrder(Long order) {
    this.order = order;
  }


  public ExecutionResource executionStage(ExecutionStageEnum executionStage) {
    
    this.executionStage = executionStage;
    return this;
  }

   /**
   * Get executionStage
   * @return executionStage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_EXECUTION_STAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ExecutionStageEnum getExecutionStage() {
    return executionStage;
  }


  public void setExecutionStage(ExecutionStageEnum executionStage) {
    this.executionStage = executionStage;
  }


  public ExecutionResource webUrl(String webUrl) {
    
    this.webUrl = webUrl;
    return this;
  }

   /**
   * Get webUrl
   * @return webUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_WEB_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getWebUrl() {
    return webUrl;
  }


  public void setWebUrl(String webUrl) {
    this.webUrl = webUrl;
  }


  public ExecutionResource testSuiteCollections(List<TestSuiteCollectionEntityResource> testSuiteCollections) {
    
    this.testSuiteCollections = testSuiteCollections;
    return this;
  }

  public ExecutionResource addTestSuiteCollectionsItem(TestSuiteCollectionEntityResource testSuiteCollectionsItem) {
    if (this.testSuiteCollections == null) {
      this.testSuiteCollections = new ArrayList<>();
    }
    this.testSuiteCollections.add(testSuiteCollectionsItem);
    return this;
  }

   /**
   * Get testSuiteCollections
   * @return testSuiteCollections
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TEST_SUITE_COLLECTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<TestSuiteCollectionEntityResource> getTestSuiteCollections() {
    return testSuiteCollections;
  }


  public void setTestSuiteCollections(List<TestSuiteCollectionEntityResource> testSuiteCollections) {
    this.testSuiteCollections = testSuiteCollections;
  }


  public ExecutionResource executionTestSuiteResources(List<ExecutionTestSuiteResource> executionTestSuiteResources) {
    
    this.executionTestSuiteResources = executionTestSuiteResources;
    return this;
  }

  public ExecutionResource addExecutionTestSuiteResourcesItem(ExecutionTestSuiteResource executionTestSuiteResourcesItem) {
    if (this.executionTestSuiteResources == null) {
      this.executionTestSuiteResources = new ArrayList<>();
    }
    this.executionTestSuiteResources.add(executionTestSuiteResourcesItem);
    return this;
  }

   /**
   * Get executionTestSuiteResources
   * @return executionTestSuiteResources
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_EXECUTION_TEST_SUITE_RESOURCES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ExecutionTestSuiteResource> getExecutionTestSuiteResources() {
    return executionTestSuiteResources;
  }


  public void setExecutionTestSuiteResources(List<ExecutionTestSuiteResource> executionTestSuiteResources) {
    this.executionTestSuiteResources = executionTestSuiteResources;
  }


  public ExecutionResource release(ReleaseResource release) {
    
    this.release = release;
    return this;
  }

   /**
   * Get release
   * @return release
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RELEASE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ReleaseResource getRelease() {
    return release;
  }


  public void setRelease(ReleaseResource release) {
    this.release = release;
  }


  public ExecutionResource hasComment(Boolean hasComment) {
    
    this.hasComment = hasComment;
    return this;
  }

   /**
   * Get hasComment
   * @return hasComment
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_HAS_COMMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getHasComment() {
    return hasComment;
  }


  public void setHasComment(Boolean hasComment) {
    this.hasComment = hasComment;
  }


  public ExecutionResource user(UserResource user) {
    
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_USER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UserResource getUser() {
    return user;
  }


  public void setUser(UserResource user) {
    this.user = user;
  }


  public ExecutionResource sessionId(String sessionId) {
    
    this.sessionId = sessionId;
    return this;
  }

   /**
   * Get sessionId
   * @return sessionId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SESSION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSessionId() {
    return sessionId;
  }


  public void setSessionId(String sessionId) {
    this.sessionId = sessionId;
  }


  public ExecutionResource buildLabel(String buildLabel) {
    
    this.buildLabel = buildLabel;
    return this;
  }

   /**
   * Get buildLabel
   * @return buildLabel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_BUILD_LABEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBuildLabel() {
    return buildLabel;
  }


  public void setBuildLabel(String buildLabel) {
    this.buildLabel = buildLabel;
  }


  public ExecutionResource buildUrl(String buildUrl) {
    
    this.buildUrl = buildUrl;
    return this;
  }

   /**
   * Get buildUrl
   * @return buildUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_BUILD_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBuildUrl() {
    return buildUrl;
  }


  public void setBuildUrl(String buildUrl) {
    this.buildUrl = buildUrl;
  }


  public ExecutionResource type(TypeEnum type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TypeEnum getType() {
    return type;
  }


  public void setType(TypeEnum type) {
    this.type = type;
  }


  public ExecutionResource jobs(List<JobResource> jobs) {
    
    this.jobs = jobs;
    return this;
  }

  public ExecutionResource addJobsItem(JobResource jobsItem) {
    if (this.jobs == null) {
      this.jobs = new ArrayList<>();
    }
    this.jobs.add(jobsItem);
    return this;
  }

   /**
   * Get jobs
   * @return jobs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_JOBS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<JobResource> getJobs() {
    return jobs;
  }


  public void setJobs(List<JobResource> jobs) {
    this.jobs = jobs;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExecutionResource executionResource = (ExecutionResource) o;
    return Objects.equals(this.status, executionResource.status) &&
        Objects.equals(this.startTime, executionResource.startTime) &&
        Objects.equals(this.endTime, executionResource.endTime) &&
        Objects.equals(this.duration, executionResource.duration) &&
        Objects.equals(this.elapsedDuration, executionResource.elapsedDuration) &&
        Objects.equals(this.totalTests, executionResource.totalTests) &&
        Objects.equals(this.totalPassedTests, executionResource.totalPassedTests) &&
        Objects.equals(this.totalFailedTests, executionResource.totalFailedTests) &&
        Objects.equals(this.totalErrorTests, executionResource.totalErrorTests) &&
        Objects.equals(this.totalIncompleteTests, executionResource.totalIncompleteTests) &&
        Objects.equals(this.totalDiffTests, executionResource.totalDiffTests) &&
        Objects.equals(this.totalDiffPassedTests, executionResource.totalDiffPassedTests) &&
        Objects.equals(this.totalDiffFailedTests, executionResource.totalDiffFailedTests) &&
        Objects.equals(this.totalDiffErrorTests, executionResource.totalDiffErrorTests) &&
        Objects.equals(this.totalDiffIncompleteTests, executionResource.totalDiffIncompleteTests) &&
        Objects.equals(this.id, executionResource.id) &&
        Objects.equals(this.projectId, executionResource.projectId) &&
        Objects.equals(this.project, executionResource.project) &&
        Objects.equals(this.buildId, executionResource.buildId) &&
        Objects.equals(this.order, executionResource.order) &&
        Objects.equals(this.executionStage, executionResource.executionStage) &&
        Objects.equals(this.webUrl, executionResource.webUrl) &&
        Objects.equals(this.testSuiteCollections, executionResource.testSuiteCollections) &&
        Objects.equals(this.executionTestSuiteResources, executionResource.executionTestSuiteResources) &&
        Objects.equals(this.release, executionResource.release) &&
        Objects.equals(this.hasComment, executionResource.hasComment) &&
        Objects.equals(this.user, executionResource.user) &&
        Objects.equals(this.sessionId, executionResource.sessionId) &&
        Objects.equals(this.buildLabel, executionResource.buildLabel) &&
        Objects.equals(this.buildUrl, executionResource.buildUrl) &&
        Objects.equals(this.type, executionResource.type) &&
        Objects.equals(this.jobs, executionResource.jobs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, startTime, endTime, duration, elapsedDuration, totalTests, totalPassedTests, totalFailedTests, totalErrorTests, totalIncompleteTests, totalDiffTests, totalDiffPassedTests, totalDiffFailedTests, totalDiffErrorTests, totalDiffIncompleteTests, id, projectId, project, buildId, order, executionStage, webUrl, testSuiteCollections, executionTestSuiteResources, release, hasComment, user, sessionId, buildLabel, buildUrl, type, jobs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExecutionResource {\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    elapsedDuration: ").append(toIndentedString(elapsedDuration)).append("\n");
    sb.append("    totalTests: ").append(toIndentedString(totalTests)).append("\n");
    sb.append("    totalPassedTests: ").append(toIndentedString(totalPassedTests)).append("\n");
    sb.append("    totalFailedTests: ").append(toIndentedString(totalFailedTests)).append("\n");
    sb.append("    totalErrorTests: ").append(toIndentedString(totalErrorTests)).append("\n");
    sb.append("    totalIncompleteTests: ").append(toIndentedString(totalIncompleteTests)).append("\n");
    sb.append("    totalDiffTests: ").append(toIndentedString(totalDiffTests)).append("\n");
    sb.append("    totalDiffPassedTests: ").append(toIndentedString(totalDiffPassedTests)).append("\n");
    sb.append("    totalDiffFailedTests: ").append(toIndentedString(totalDiffFailedTests)).append("\n");
    sb.append("    totalDiffErrorTests: ").append(toIndentedString(totalDiffErrorTests)).append("\n");
    sb.append("    totalDiffIncompleteTests: ").append(toIndentedString(totalDiffIncompleteTests)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    project: ").append(toIndentedString(project)).append("\n");
    sb.append("    buildId: ").append(toIndentedString(buildId)).append("\n");
    sb.append("    order: ").append(toIndentedString(order)).append("\n");
    sb.append("    executionStage: ").append(toIndentedString(executionStage)).append("\n");
    sb.append("    webUrl: ").append(toIndentedString(webUrl)).append("\n");
    sb.append("    testSuiteCollections: ").append(toIndentedString(testSuiteCollections)).append("\n");
    sb.append("    executionTestSuiteResources: ").append(toIndentedString(executionTestSuiteResources)).append("\n");
    sb.append("    release: ").append(toIndentedString(release)).append("\n");
    sb.append("    hasComment: ").append(toIndentedString(hasComment)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    sessionId: ").append(toIndentedString(sessionId)).append("\n");
    sb.append("    buildLabel: ").append(toIndentedString(buildLabel)).append("\n");
    sb.append("    buildUrl: ").append(toIndentedString(buildUrl)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    jobs: ").append(toIndentedString(jobs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

