/*
 * Katalon TestOps API reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.katalon.testops.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.katalon.testops.api.model.RunConfigurationResource;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * SchedulerResource
 */
@JsonPropertyOrder({
  SchedulerResource.JSON_PROPERTY_ID,
  SchedulerResource.JSON_PROPERTY_NAME,
  SchedulerResource.JSON_PROPERTY_START_TIME,
  SchedulerResource.JSON_PROPERTY_NEXT_TIME,
  SchedulerResource.JSON_PROPERTY_END_TIME,
  SchedulerResource.JSON_PROPERTY_ACTIVE,
  SchedulerResource.JSON_PROPERTY_INTERVAL,
  SchedulerResource.JSON_PROPERTY_INTERVAL_UNIT,
  SchedulerResource.JSON_PROPERTY_RUN_CONFIGURATION_ID,
  SchedulerResource.JSON_PROPERTY_RUN_CONFIGURATION
})
@JsonTypeName("SchedulerResource")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SchedulerResource implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_ID = "id";
  private Long id;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_START_TIME = "startTime";
  private OffsetDateTime startTime;

  public static final String JSON_PROPERTY_NEXT_TIME = "nextTime";
  private OffsetDateTime nextTime;

  public static final String JSON_PROPERTY_END_TIME = "endTime";
  private OffsetDateTime endTime;

  public static final String JSON_PROPERTY_ACTIVE = "active";
  private Boolean active;

  public static final String JSON_PROPERTY_INTERVAL = "interval";
  private Integer interval;

  /**
   * Gets or Sets intervalUnit
   */
  public enum IntervalUnitEnum {
    MINUTE("MINUTE"),
    
    HOUR("HOUR"),
    
    DAY("DAY"),
    
    WEEK("WEEK"),
    
    MONTH("MONTH");

    private String value;

    IntervalUnitEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static IntervalUnitEnum fromValue(String value) {
      for (IntervalUnitEnum b : IntervalUnitEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_INTERVAL_UNIT = "intervalUnit";
  private IntervalUnitEnum intervalUnit;

  public static final String JSON_PROPERTY_RUN_CONFIGURATION_ID = "runConfigurationId";
  private Long runConfigurationId;

  public static final String JSON_PROPERTY_RUN_CONFIGURATION = "runConfiguration";
  private RunConfigurationResource runConfiguration;


  public SchedulerResource id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  public void setId(Long id) {
    this.id = id;
  }


  public SchedulerResource name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public SchedulerResource startTime(OffsetDateTime startTime) {
    
    this.startTime = startTime;
    return this;
  }

   /**
   * Get startTime
   * @return startTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_START_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getStartTime() {
    return startTime;
  }


  public void setStartTime(OffsetDateTime startTime) {
    this.startTime = startTime;
  }


  public SchedulerResource nextTime(OffsetDateTime nextTime) {
    
    this.nextTime = nextTime;
    return this;
  }

   /**
   * Get nextTime
   * @return nextTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NEXT_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getNextTime() {
    return nextTime;
  }


  public void setNextTime(OffsetDateTime nextTime) {
    this.nextTime = nextTime;
  }


  public SchedulerResource endTime(OffsetDateTime endTime) {
    
    this.endTime = endTime;
    return this;
  }

   /**
   * Get endTime
   * @return endTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_END_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getEndTime() {
    return endTime;
  }


  public void setEndTime(OffsetDateTime endTime) {
    this.endTime = endTime;
  }


  public SchedulerResource active(Boolean active) {
    
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ACTIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getActive() {
    return active;
  }


  public void setActive(Boolean active) {
    this.active = active;
  }


  public SchedulerResource interval(Integer interval) {
    
    this.interval = interval;
    return this;
  }

   /**
   * Get interval
   * @return interval
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_INTERVAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getInterval() {
    return interval;
  }


  public void setInterval(Integer interval) {
    this.interval = interval;
  }


  public SchedulerResource intervalUnit(IntervalUnitEnum intervalUnit) {
    
    this.intervalUnit = intervalUnit;
    return this;
  }

   /**
   * Get intervalUnit
   * @return intervalUnit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_INTERVAL_UNIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public IntervalUnitEnum getIntervalUnit() {
    return intervalUnit;
  }


  public void setIntervalUnit(IntervalUnitEnum intervalUnit) {
    this.intervalUnit = intervalUnit;
  }


  public SchedulerResource runConfigurationId(Long runConfigurationId) {
    
    this.runConfigurationId = runConfigurationId;
    return this;
  }

   /**
   * Get runConfigurationId
   * @return runConfigurationId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RUN_CONFIGURATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getRunConfigurationId() {
    return runConfigurationId;
  }


  public void setRunConfigurationId(Long runConfigurationId) {
    this.runConfigurationId = runConfigurationId;
  }


  public SchedulerResource runConfiguration(RunConfigurationResource runConfiguration) {
    
    this.runConfiguration = runConfiguration;
    return this;
  }

   /**
   * Get runConfiguration
   * @return runConfiguration
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RUN_CONFIGURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RunConfigurationResource getRunConfiguration() {
    return runConfiguration;
  }


  public void setRunConfiguration(RunConfigurationResource runConfiguration) {
    this.runConfiguration = runConfiguration;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SchedulerResource schedulerResource = (SchedulerResource) o;
    return Objects.equals(this.id, schedulerResource.id) &&
        Objects.equals(this.name, schedulerResource.name) &&
        Objects.equals(this.startTime, schedulerResource.startTime) &&
        Objects.equals(this.nextTime, schedulerResource.nextTime) &&
        Objects.equals(this.endTime, schedulerResource.endTime) &&
        Objects.equals(this.active, schedulerResource.active) &&
        Objects.equals(this.interval, schedulerResource.interval) &&
        Objects.equals(this.intervalUnit, schedulerResource.intervalUnit) &&
        Objects.equals(this.runConfigurationId, schedulerResource.runConfigurationId) &&
        Objects.equals(this.runConfiguration, schedulerResource.runConfiguration);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, startTime, nextTime, endTime, active, interval, intervalUnit, runConfigurationId, runConfiguration);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SchedulerResource {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    nextTime: ").append(toIndentedString(nextTime)).append("\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    interval: ").append(toIndentedString(interval)).append("\n");
    sb.append("    intervalUnit: ").append(toIndentedString(intervalUnit)).append("\n");
    sb.append("    runConfigurationId: ").append(toIndentedString(runConfigurationId)).append("\n");
    sb.append("    runConfiguration: ").append(toIndentedString(runConfiguration)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

