/*
 * Katalon TestOps API reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.katalon.testops.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * SearchConfigResource
 */
@JsonPropertyOrder({
  SearchConfigResource.JSON_PROPERTY_FILTER_CONFIG,
  SearchConfigResource.JSON_PROPERTY_SORT_DEFAULT,
  SearchConfigResource.JSON_PROPERTY_SORT_CONFIG
})
@JsonTypeName("SearchConfigResource")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SearchConfigResource implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_FILTER_CONFIG = "filterConfig";
  private Map<String, String> filterConfig = null;

  public static final String JSON_PROPERTY_SORT_DEFAULT = "sortDefault";
  private List<String> sortDefault = null;

  public static final String JSON_PROPERTY_SORT_CONFIG = "sortConfig";
  private List<String> sortConfig = null;


  public SearchConfigResource filterConfig(Map<String, String> filterConfig) {
    
    this.filterConfig = filterConfig;
    return this;
  }

  public SearchConfigResource putFilterConfigItem(String key, String filterConfigItem) {
    if (this.filterConfig == null) {
      this.filterConfig = new HashMap<>();
    }
    this.filterConfig.put(key, filterConfigItem);
    return this;
  }

   /**
   * Get filterConfig
   * @return filterConfig
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FILTER_CONFIG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, String> getFilterConfig() {
    return filterConfig;
  }


  public void setFilterConfig(Map<String, String> filterConfig) {
    this.filterConfig = filterConfig;
  }


  public SearchConfigResource sortDefault(List<String> sortDefault) {
    
    this.sortDefault = sortDefault;
    return this;
  }

  public SearchConfigResource addSortDefaultItem(String sortDefaultItem) {
    if (this.sortDefault == null) {
      this.sortDefault = new ArrayList<>();
    }
    this.sortDefault.add(sortDefaultItem);
    return this;
  }

   /**
   * Get sortDefault
   * @return sortDefault
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SORT_DEFAULT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getSortDefault() {
    return sortDefault;
  }


  public void setSortDefault(List<String> sortDefault) {
    this.sortDefault = sortDefault;
  }


  public SearchConfigResource sortConfig(List<String> sortConfig) {
    
    this.sortConfig = sortConfig;
    return this;
  }

  public SearchConfigResource addSortConfigItem(String sortConfigItem) {
    if (this.sortConfig == null) {
      this.sortConfig = new ArrayList<>();
    }
    this.sortConfig.add(sortConfigItem);
    return this;
  }

   /**
   * Get sortConfig
   * @return sortConfig
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SORT_CONFIG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getSortConfig() {
    return sortConfig;
  }


  public void setSortConfig(List<String> sortConfig) {
    this.sortConfig = sortConfig;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchConfigResource searchConfigResource = (SearchConfigResource) o;
    return Objects.equals(this.filterConfig, searchConfigResource.filterConfig) &&
        Objects.equals(this.sortDefault, searchConfigResource.sortDefault) &&
        Objects.equals(this.sortConfig, searchConfigResource.sortConfig);
  }

  @Override
  public int hashCode() {
    return Objects.hash(filterConfig, sortDefault, sortConfig);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchConfigResource {\n");
    sb.append("    filterConfig: ").append(toIndentedString(filterConfig)).append("\n");
    sb.append("    sortDefault: ").append(toIndentedString(sortDefault)).append("\n");
    sb.append("    sortConfig: ").append(toIndentedString(sortConfig)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

