/*
 * Katalon TestOps API reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.katalon.testops.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.katalon.testops.api.model.PlatformResource;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * TestCasePlatformStatisticsResource
 */
@JsonPropertyOrder({
  TestCasePlatformStatisticsResource.JSON_PROPERTY_TOTAL_TESTS,
  TestCasePlatformStatisticsResource.JSON_PROPERTY_TOTAL_PASSED_TESTS,
  TestCasePlatformStatisticsResource.JSON_PROPERTY_TOTAL_FAILED_TESTS,
  TestCasePlatformStatisticsResource.JSON_PROPERTY_TOTAL_ERROR_TESTS,
  TestCasePlatformStatisticsResource.JSON_PROPERTY_TOTAL_INCOMPLETE_TESTS,
  TestCasePlatformStatisticsResource.JSON_PROPERTY_PLATFORM,
  TestCasePlatformStatisticsResource.JSON_PROPERTY_PLATFORM_ID
})
@JsonTypeName("TestCasePlatformStatisticsResource")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class TestCasePlatformStatisticsResource implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_TOTAL_TESTS = "totalTests";
  private Long totalTests;

  public static final String JSON_PROPERTY_TOTAL_PASSED_TESTS = "totalPassedTests";
  private Long totalPassedTests;

  public static final String JSON_PROPERTY_TOTAL_FAILED_TESTS = "totalFailedTests";
  private Long totalFailedTests;

  public static final String JSON_PROPERTY_TOTAL_ERROR_TESTS = "totalErrorTests";
  private Long totalErrorTests;

  public static final String JSON_PROPERTY_TOTAL_INCOMPLETE_TESTS = "totalIncompleteTests";
  private Long totalIncompleteTests;

  public static final String JSON_PROPERTY_PLATFORM = "platform";
  private PlatformResource platform;

  public static final String JSON_PROPERTY_PLATFORM_ID = "platformId";
  private Long platformId;


  public TestCasePlatformStatisticsResource totalTests(Long totalTests) {
    
    this.totalTests = totalTests;
    return this;
  }

   /**
   * Get totalTests
   * @return totalTests
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TOTAL_TESTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTotalTests() {
    return totalTests;
  }


  public void setTotalTests(Long totalTests) {
    this.totalTests = totalTests;
  }


  public TestCasePlatformStatisticsResource totalPassedTests(Long totalPassedTests) {
    
    this.totalPassedTests = totalPassedTests;
    return this;
  }

   /**
   * Get totalPassedTests
   * @return totalPassedTests
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TOTAL_PASSED_TESTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTotalPassedTests() {
    return totalPassedTests;
  }


  public void setTotalPassedTests(Long totalPassedTests) {
    this.totalPassedTests = totalPassedTests;
  }


  public TestCasePlatformStatisticsResource totalFailedTests(Long totalFailedTests) {
    
    this.totalFailedTests = totalFailedTests;
    return this;
  }

   /**
   * Get totalFailedTests
   * @return totalFailedTests
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TOTAL_FAILED_TESTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTotalFailedTests() {
    return totalFailedTests;
  }


  public void setTotalFailedTests(Long totalFailedTests) {
    this.totalFailedTests = totalFailedTests;
  }


  public TestCasePlatformStatisticsResource totalErrorTests(Long totalErrorTests) {
    
    this.totalErrorTests = totalErrorTests;
    return this;
  }

   /**
   * Get totalErrorTests
   * @return totalErrorTests
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TOTAL_ERROR_TESTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTotalErrorTests() {
    return totalErrorTests;
  }


  public void setTotalErrorTests(Long totalErrorTests) {
    this.totalErrorTests = totalErrorTests;
  }


  public TestCasePlatformStatisticsResource totalIncompleteTests(Long totalIncompleteTests) {
    
    this.totalIncompleteTests = totalIncompleteTests;
    return this;
  }

   /**
   * Get totalIncompleteTests
   * @return totalIncompleteTests
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TOTAL_INCOMPLETE_TESTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTotalIncompleteTests() {
    return totalIncompleteTests;
  }


  public void setTotalIncompleteTests(Long totalIncompleteTests) {
    this.totalIncompleteTests = totalIncompleteTests;
  }


  public TestCasePlatformStatisticsResource platform(PlatformResource platform) {
    
    this.platform = platform;
    return this;
  }

   /**
   * Get platform
   * @return platform
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PLATFORM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PlatformResource getPlatform() {
    return platform;
  }


  public void setPlatform(PlatformResource platform) {
    this.platform = platform;
  }


  public TestCasePlatformStatisticsResource platformId(Long platformId) {
    
    this.platformId = platformId;
    return this;
  }

   /**
   * Get platformId
   * @return platformId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PLATFORM_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getPlatformId() {
    return platformId;
  }


  public void setPlatformId(Long platformId) {
    this.platformId = platformId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TestCasePlatformStatisticsResource testCasePlatformStatisticsResource = (TestCasePlatformStatisticsResource) o;
    return Objects.equals(this.totalTests, testCasePlatformStatisticsResource.totalTests) &&
        Objects.equals(this.totalPassedTests, testCasePlatformStatisticsResource.totalPassedTests) &&
        Objects.equals(this.totalFailedTests, testCasePlatformStatisticsResource.totalFailedTests) &&
        Objects.equals(this.totalErrorTests, testCasePlatformStatisticsResource.totalErrorTests) &&
        Objects.equals(this.totalIncompleteTests, testCasePlatformStatisticsResource.totalIncompleteTests) &&
        Objects.equals(this.platform, testCasePlatformStatisticsResource.platform) &&
        Objects.equals(this.platformId, testCasePlatformStatisticsResource.platformId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalTests, totalPassedTests, totalFailedTests, totalErrorTests, totalIncompleteTests, platform, platformId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TestCasePlatformStatisticsResource {\n");
    sb.append("    totalTests: ").append(toIndentedString(totalTests)).append("\n");
    sb.append("    totalPassedTests: ").append(toIndentedString(totalPassedTests)).append("\n");
    sb.append("    totalFailedTests: ").append(toIndentedString(totalFailedTests)).append("\n");
    sb.append("    totalErrorTests: ").append(toIndentedString(totalErrorTests)).append("\n");
    sb.append("    totalIncompleteTests: ").append(toIndentedString(totalIncompleteTests)).append("\n");
    sb.append("    platform: ").append(toIndentedString(platform)).append("\n");
    sb.append("    platformId: ").append(toIndentedString(platformId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

