/*
 * Katalon TestOps API reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.katalon.testops.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.katalon.testops.api.model.ExecutionTestResultResource;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * TestResultAssertionFailedResource
 */
@JsonPropertyOrder({
  TestResultAssertionFailedResource.JSON_PROPERTY_ID,
  TestResultAssertionFailedResource.JSON_PROPERTY_EXECUTION_TEST_RESULT_ID,
  TestResultAssertionFailedResource.JSON_PROPERTY_EXECUTION_TEST_RESULT_RESOURCE,
  TestResultAssertionFailedResource.JSON_PROPERTY_STACKTRACE,
  TestResultAssertionFailedResource.JSON_PROPERTY_MESSAGE,
  TestResultAssertionFailedResource.JSON_PROPERTY_LOG_TIME
})
@JsonTypeName("TestResultAssertionFailedResource")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class TestResultAssertionFailedResource implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_ID = "id";
  private Long id;

  public static final String JSON_PROPERTY_EXECUTION_TEST_RESULT_ID = "executionTestResultId";
  private Long executionTestResultId;

  public static final String JSON_PROPERTY_EXECUTION_TEST_RESULT_RESOURCE = "executionTestResultResource";
  private ExecutionTestResultResource executionTestResultResource;

  public static final String JSON_PROPERTY_STACKTRACE = "stacktrace";
  private String stacktrace;

  public static final String JSON_PROPERTY_MESSAGE = "message";
  private String message;

  public static final String JSON_PROPERTY_LOG_TIME = "logTime";
  private String logTime;


  public TestResultAssertionFailedResource id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  public void setId(Long id) {
    this.id = id;
  }


  public TestResultAssertionFailedResource executionTestResultId(Long executionTestResultId) {
    
    this.executionTestResultId = executionTestResultId;
    return this;
  }

   /**
   * Get executionTestResultId
   * @return executionTestResultId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_EXECUTION_TEST_RESULT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getExecutionTestResultId() {
    return executionTestResultId;
  }


  public void setExecutionTestResultId(Long executionTestResultId) {
    this.executionTestResultId = executionTestResultId;
  }


  public TestResultAssertionFailedResource executionTestResultResource(ExecutionTestResultResource executionTestResultResource) {
    
    this.executionTestResultResource = executionTestResultResource;
    return this;
  }

   /**
   * Get executionTestResultResource
   * @return executionTestResultResource
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_EXECUTION_TEST_RESULT_RESOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ExecutionTestResultResource getExecutionTestResultResource() {
    return executionTestResultResource;
  }


  public void setExecutionTestResultResource(ExecutionTestResultResource executionTestResultResource) {
    this.executionTestResultResource = executionTestResultResource;
  }


  public TestResultAssertionFailedResource stacktrace(String stacktrace) {
    
    this.stacktrace = stacktrace;
    return this;
  }

   /**
   * Get stacktrace
   * @return stacktrace
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STACKTRACE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStacktrace() {
    return stacktrace;
  }


  public void setStacktrace(String stacktrace) {
    this.stacktrace = stacktrace;
  }


  public TestResultAssertionFailedResource message(String message) {
    
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMessage() {
    return message;
  }


  public void setMessage(String message) {
    this.message = message;
  }


  public TestResultAssertionFailedResource logTime(String logTime) {
    
    this.logTime = logTime;
    return this;
  }

   /**
   * Get logTime
   * @return logTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LOG_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLogTime() {
    return logTime;
  }


  public void setLogTime(String logTime) {
    this.logTime = logTime;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TestResultAssertionFailedResource testResultAssertionFailedResource = (TestResultAssertionFailedResource) o;
    return Objects.equals(this.id, testResultAssertionFailedResource.id) &&
        Objects.equals(this.executionTestResultId, testResultAssertionFailedResource.executionTestResultId) &&
        Objects.equals(this.executionTestResultResource, testResultAssertionFailedResource.executionTestResultResource) &&
        Objects.equals(this.stacktrace, testResultAssertionFailedResource.stacktrace) &&
        Objects.equals(this.message, testResultAssertionFailedResource.message) &&
        Objects.equals(this.logTime, testResultAssertionFailedResource.logTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, executionTestResultId, executionTestResultResource, stacktrace, message, logTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TestResultAssertionFailedResource {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    executionTestResultId: ").append(toIndentedString(executionTestResultId)).append("\n");
    sb.append("    executionTestResultResource: ").append(toIndentedString(executionTestResultResource)).append("\n");
    sb.append("    stacktrace: ").append(toIndentedString(stacktrace)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    logTime: ").append(toIndentedString(logTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

