/*
 * Katalon TestOps API reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.katalon.testops.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.katalon.testops.api.model.TimeZoneResourceOffsetRules;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * TimeZoneResourceOffset
 */
@JsonPropertyOrder({
  TimeZoneResourceOffset.JSON_PROPERTY_TOTAL_SECONDS,
  TimeZoneResourceOffset.JSON_PROPERTY_ID,
  TimeZoneResourceOffset.JSON_PROPERTY_RULES
})
@JsonTypeName("TimeZoneResource_offset")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class TimeZoneResourceOffset implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_TOTAL_SECONDS = "totalSeconds";
  private Integer totalSeconds;

  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_RULES = "rules";
  private TimeZoneResourceOffsetRules rules;


  public TimeZoneResourceOffset totalSeconds(Integer totalSeconds) {
    
    this.totalSeconds = totalSeconds;
    return this;
  }

   /**
   * Get totalSeconds
   * @return totalSeconds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TOTAL_SECONDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTotalSeconds() {
    return totalSeconds;
  }


  public void setTotalSeconds(Integer totalSeconds) {
    this.totalSeconds = totalSeconds;
  }


  public TimeZoneResourceOffset id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public TimeZoneResourceOffset rules(TimeZoneResourceOffsetRules rules) {
    
    this.rules = rules;
    return this;
  }

   /**
   * Get rules
   * @return rules
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RULES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TimeZoneResourceOffsetRules getRules() {
    return rules;
  }


  public void setRules(TimeZoneResourceOffsetRules rules) {
    this.rules = rules;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TimeZoneResourceOffset timeZoneResourceOffset = (TimeZoneResourceOffset) o;
    return Objects.equals(this.totalSeconds, timeZoneResourceOffset.totalSeconds) &&
        Objects.equals(this.id, timeZoneResourceOffset.id) &&
        Objects.equals(this.rules, timeZoneResourceOffset.rules);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalSeconds, id, rules);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TimeZoneResourceOffset {\n");
    sb.append("    totalSeconds: ").append(toIndentedString(totalSeconds)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    rules: ").append(toIndentedString(rules)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

