/*
 * Katalon TestOps API reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.katalon.testops.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.katalon.testops.api.model.TimeZoneResourceOffsetRulesDurationUnits;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * TimeZoneResourceOffsetRulesDuration
 */
@JsonPropertyOrder({
  TimeZoneResourceOffsetRulesDuration.JSON_PROPERTY_SECONDS,
  TimeZoneResourceOffsetRulesDuration.JSON_PROPERTY_NANO,
  TimeZoneResourceOffsetRulesDuration.JSON_PROPERTY_ZERO,
  TimeZoneResourceOffsetRulesDuration.JSON_PROPERTY_NEGATIVE,
  TimeZoneResourceOffsetRulesDuration.JSON_PROPERTY_UNITS
})
@JsonTypeName("TimeZoneResource_offset_rules_duration")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class TimeZoneResourceOffsetRulesDuration implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_SECONDS = "seconds";
  private Long seconds;

  public static final String JSON_PROPERTY_NANO = "nano";
  private Integer nano;

  public static final String JSON_PROPERTY_ZERO = "zero";
  private Boolean zero;

  public static final String JSON_PROPERTY_NEGATIVE = "negative";
  private Boolean negative;

  public static final String JSON_PROPERTY_UNITS = "units";
  private List<TimeZoneResourceOffsetRulesDurationUnits> units = null;


  public TimeZoneResourceOffsetRulesDuration seconds(Long seconds) {
    
    this.seconds = seconds;
    return this;
  }

   /**
   * Get seconds
   * @return seconds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SECONDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getSeconds() {
    return seconds;
  }


  public void setSeconds(Long seconds) {
    this.seconds = seconds;
  }


  public TimeZoneResourceOffsetRulesDuration nano(Integer nano) {
    
    this.nano = nano;
    return this;
  }

   /**
   * Get nano
   * @return nano
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NANO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getNano() {
    return nano;
  }


  public void setNano(Integer nano) {
    this.nano = nano;
  }


  public TimeZoneResourceOffsetRulesDuration zero(Boolean zero) {
    
    this.zero = zero;
    return this;
  }

   /**
   * Get zero
   * @return zero
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ZERO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getZero() {
    return zero;
  }


  public void setZero(Boolean zero) {
    this.zero = zero;
  }


  public TimeZoneResourceOffsetRulesDuration negative(Boolean negative) {
    
    this.negative = negative;
    return this;
  }

   /**
   * Get negative
   * @return negative
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NEGATIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getNegative() {
    return negative;
  }


  public void setNegative(Boolean negative) {
    this.negative = negative;
  }


  public TimeZoneResourceOffsetRulesDuration units(List<TimeZoneResourceOffsetRulesDurationUnits> units) {
    
    this.units = units;
    return this;
  }

  public TimeZoneResourceOffsetRulesDuration addUnitsItem(TimeZoneResourceOffsetRulesDurationUnits unitsItem) {
    if (this.units == null) {
      this.units = new ArrayList<>();
    }
    this.units.add(unitsItem);
    return this;
  }

   /**
   * Get units
   * @return units
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_UNITS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<TimeZoneResourceOffsetRulesDurationUnits> getUnits() {
    return units;
  }


  public void setUnits(List<TimeZoneResourceOffsetRulesDurationUnits> units) {
    this.units = units;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TimeZoneResourceOffsetRulesDuration timeZoneResourceOffsetRulesDuration = (TimeZoneResourceOffsetRulesDuration) o;
    return Objects.equals(this.seconds, timeZoneResourceOffsetRulesDuration.seconds) &&
        Objects.equals(this.nano, timeZoneResourceOffsetRulesDuration.nano) &&
        Objects.equals(this.zero, timeZoneResourceOffsetRulesDuration.zero) &&
        Objects.equals(this.negative, timeZoneResourceOffsetRulesDuration.negative) &&
        Objects.equals(this.units, timeZoneResourceOffsetRulesDuration.units);
  }

  @Override
  public int hashCode() {
    return Objects.hash(seconds, nano, zero, negative, units);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TimeZoneResourceOffsetRulesDuration {\n");
    sb.append("    seconds: ").append(toIndentedString(seconds)).append("\n");
    sb.append("    nano: ").append(toIndentedString(nano)).append("\n");
    sb.append("    zero: ").append(toIndentedString(zero)).append("\n");
    sb.append("    negative: ").append(toIndentedString(negative)).append("\n");
    sb.append("    units: ").append(toIndentedString(units)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

