/*
 * Katalon TestOps API reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.katalon.testops.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.katalon.testops.api.model.OrganizationResource;
import com.katalon.testops.api.model.UserResource;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * UserOrganizationFeatureResource
 */
@JsonPropertyOrder({
  UserOrganizationFeatureResource.JSON_PROPERTY_USER,
  UserOrganizationFeatureResource.JSON_PROPERTY_USER_ID,
  UserOrganizationFeatureResource.JSON_PROPERTY_ORGANIZATION_ID,
  UserOrganizationFeatureResource.JSON_PROPERTY_USER_EMAIL,
  UserOrganizationFeatureResource.JSON_PROPERTY_ORGANIZATION,
  UserOrganizationFeatureResource.JSON_PROPERTY_FEATURE
})
@JsonTypeName("UserOrganizationFeatureResource")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class UserOrganizationFeatureResource implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_USER = "user";
  private UserResource user;

  public static final String JSON_PROPERTY_USER_ID = "userId";
  private Long userId;

  public static final String JSON_PROPERTY_ORGANIZATION_ID = "organizationId";
  private Long organizationId;

  public static final String JSON_PROPERTY_USER_EMAIL = "userEmail";
  private String userEmail;

  public static final String JSON_PROPERTY_ORGANIZATION = "organization";
  private OrganizationResource organization;

  /**
   * Gets or Sets feature
   */
  public enum FeatureEnum {
    KSE("KSE"),
    
    ENGINE("ENGINE"),
    
    TESTOPS("TESTOPS"),
    
    FLOATING_ENGINE("FLOATING_ENGINE"),
    
    UNLIMITED_KSE("UNLIMITED_KSE"),
    
    UNLIMITED_ENGINE("UNLIMITED_ENGINE");

    private String value;

    FeatureEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static FeatureEnum fromValue(String value) {
      for (FeatureEnum b : FeatureEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_FEATURE = "feature";
  private FeatureEnum feature;


  public UserOrganizationFeatureResource user(UserResource user) {
    
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_USER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UserResource getUser() {
    return user;
  }


  public void setUser(UserResource user) {
    this.user = user;
  }


  public UserOrganizationFeatureResource userId(Long userId) {
    
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getUserId() {
    return userId;
  }


  public void setUserId(Long userId) {
    this.userId = userId;
  }


  public UserOrganizationFeatureResource organizationId(Long organizationId) {
    
    this.organizationId = organizationId;
    return this;
  }

   /**
   * Get organizationId
   * @return organizationId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ORGANIZATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getOrganizationId() {
    return organizationId;
  }


  public void setOrganizationId(Long organizationId) {
    this.organizationId = organizationId;
  }


  public UserOrganizationFeatureResource userEmail(String userEmail) {
    
    this.userEmail = userEmail;
    return this;
  }

   /**
   * Get userEmail
   * @return userEmail
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_USER_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUserEmail() {
    return userEmail;
  }


  public void setUserEmail(String userEmail) {
    this.userEmail = userEmail;
  }


  public UserOrganizationFeatureResource organization(OrganizationResource organization) {
    
    this.organization = organization;
    return this;
  }

   /**
   * Get organization
   * @return organization
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ORGANIZATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OrganizationResource getOrganization() {
    return organization;
  }


  public void setOrganization(OrganizationResource organization) {
    this.organization = organization;
  }


  public UserOrganizationFeatureResource feature(FeatureEnum feature) {
    
    this.feature = feature;
    return this;
  }

   /**
   * Get feature
   * @return feature
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FEATURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public FeatureEnum getFeature() {
    return feature;
  }


  public void setFeature(FeatureEnum feature) {
    this.feature = feature;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserOrganizationFeatureResource userOrganizationFeatureResource = (UserOrganizationFeatureResource) o;
    return Objects.equals(this.user, userOrganizationFeatureResource.user) &&
        Objects.equals(this.userId, userOrganizationFeatureResource.userId) &&
        Objects.equals(this.organizationId, userOrganizationFeatureResource.organizationId) &&
        Objects.equals(this.userEmail, userOrganizationFeatureResource.userEmail) &&
        Objects.equals(this.organization, userOrganizationFeatureResource.organization) &&
        Objects.equals(this.feature, userOrganizationFeatureResource.feature);
  }

  @Override
  public int hashCode() {
    return Objects.hash(user, userId, organizationId, userEmail, organization, feature);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserOrganizationFeatureResource {\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    organizationId: ").append(toIndentedString(organizationId)).append("\n");
    sb.append("    userEmail: ").append(toIndentedString(userEmail)).append("\n");
    sb.append("    organization: ").append(toIndentedString(organization)).append("\n");
    sb.append("    feature: ").append(toIndentedString(feature)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

