/*
 * Katalon TestOps API reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.katalon.testops.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * UserSettingResource
 */
@JsonPropertyOrder({
  UserSettingResource.JSON_PROPERTY_MAIL_JOB_START,
  UserSettingResource.JSON_PROPERTY_MAIL_JOB_END,
  UserSettingResource.JSON_PROPERTY_MAIL_EXECUTION,
  UserSettingResource.JSON_PROPERTY_MAIL_EXECUTION_STATUS,
  UserSettingResource.JSON_PROPERTY_MAIL_WEEKLY_UPDATE
})
@JsonTypeName("UserSettingResource")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class UserSettingResource implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_MAIL_JOB_START = "mailJobStart";
  private Boolean mailJobStart;

  public static final String JSON_PROPERTY_MAIL_JOB_END = "mailJobEnd";
  private Boolean mailJobEnd;

  public static final String JSON_PROPERTY_MAIL_EXECUTION = "mailExecution";
  private Boolean mailExecution;

  public static final String JSON_PROPERTY_MAIL_EXECUTION_STATUS = "mailExecutionStatus";
  private String mailExecutionStatus;

  public static final String JSON_PROPERTY_MAIL_WEEKLY_UPDATE = "mailWeeklyUpdate";
  private Boolean mailWeeklyUpdate;


  public UserSettingResource mailJobStart(Boolean mailJobStart) {
    
    this.mailJobStart = mailJobStart;
    return this;
  }

   /**
   * Get mailJobStart
   * @return mailJobStart
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MAIL_JOB_START)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getMailJobStart() {
    return mailJobStart;
  }


  public void setMailJobStart(Boolean mailJobStart) {
    this.mailJobStart = mailJobStart;
  }


  public UserSettingResource mailJobEnd(Boolean mailJobEnd) {
    
    this.mailJobEnd = mailJobEnd;
    return this;
  }

   /**
   * Get mailJobEnd
   * @return mailJobEnd
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MAIL_JOB_END)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getMailJobEnd() {
    return mailJobEnd;
  }


  public void setMailJobEnd(Boolean mailJobEnd) {
    this.mailJobEnd = mailJobEnd;
  }


  public UserSettingResource mailExecution(Boolean mailExecution) {
    
    this.mailExecution = mailExecution;
    return this;
  }

   /**
   * Get mailExecution
   * @return mailExecution
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MAIL_EXECUTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getMailExecution() {
    return mailExecution;
  }


  public void setMailExecution(Boolean mailExecution) {
    this.mailExecution = mailExecution;
  }


  public UserSettingResource mailExecutionStatus(String mailExecutionStatus) {
    
    this.mailExecutionStatus = mailExecutionStatus;
    return this;
  }

   /**
   * Get mailExecutionStatus
   * @return mailExecutionStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MAIL_EXECUTION_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMailExecutionStatus() {
    return mailExecutionStatus;
  }


  public void setMailExecutionStatus(String mailExecutionStatus) {
    this.mailExecutionStatus = mailExecutionStatus;
  }


  public UserSettingResource mailWeeklyUpdate(Boolean mailWeeklyUpdate) {
    
    this.mailWeeklyUpdate = mailWeeklyUpdate;
    return this;
  }

   /**
   * Get mailWeeklyUpdate
   * @return mailWeeklyUpdate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MAIL_WEEKLY_UPDATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getMailWeeklyUpdate() {
    return mailWeeklyUpdate;
  }


  public void setMailWeeklyUpdate(Boolean mailWeeklyUpdate) {
    this.mailWeeklyUpdate = mailWeeklyUpdate;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserSettingResource userSettingResource = (UserSettingResource) o;
    return Objects.equals(this.mailJobStart, userSettingResource.mailJobStart) &&
        Objects.equals(this.mailJobEnd, userSettingResource.mailJobEnd) &&
        Objects.equals(this.mailExecution, userSettingResource.mailExecution) &&
        Objects.equals(this.mailExecutionStatus, userSettingResource.mailExecutionStatus) &&
        Objects.equals(this.mailWeeklyUpdate, userSettingResource.mailWeeklyUpdate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mailJobStart, mailJobEnd, mailExecution, mailExecutionStatus, mailWeeklyUpdate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserSettingResource {\n");
    sb.append("    mailJobStart: ").append(toIndentedString(mailJobStart)).append("\n");
    sb.append("    mailJobEnd: ").append(toIndentedString(mailJobEnd)).append("\n");
    sb.append("    mailExecution: ").append(toIndentedString(mailExecution)).append("\n");
    sb.append("    mailExecutionStatus: ").append(toIndentedString(mailExecutionStatus)).append("\n");
    sb.append("    mailWeeklyUpdate: ").append(toIndentedString(mailWeeklyUpdate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

