/*
 * Katalon TestOps API reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.katalon.testops.api.api;

import com.katalon.testops.api.model.FileResource;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for FileApi
 */
@Ignore
public class FileApiTest {

    private final FileApi api = new FileApi();

    
    /**
     * Downloads a file.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void download2Test() {
        Long id = null;
        api.download2(id);

        // TODO: test validations
    }
    
    /**
     * Returns an upload URL.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUploadUrlTest() {
        Long projectId = null;
        FileResource response = api.getUploadUrl(projectId);

        // TODO: test validations
    }
    
    /**
     * Returns multiple upload URLs.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUploadUrlsTest() {
        Long projectId = null;
        Long numberUrl = null;
        List<FileResource> response = api.getUploadUrls(projectId, numberUrl);

        // TODO: test validations
    }
    
}
