/*
 * Katalon TestOps API reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.katalon.testops.api.api;

import com.katalon.testops.api.model.OrganizationTrialRequestResource;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OrganizationTrialRequestResourceControllerApi
 */
@Ignore
public class OrganizationTrialRequestResourceControllerApiTest {

    private final OrganizationTrialRequestResourceControllerApi api = new OrganizationTrialRequestResourceControllerApi();

    
    /**
     * Get organization trial request data
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTrialRequestTest() {
        Long id = null;
        OrganizationTrialRequestResource response = api.getTrialRequest(id);

        // TODO: test validations
    }
    
    /**
     * Submit organization trial request
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void submitTrialRequestTest() {
        Long id = null;
        OrganizationTrialRequestResource organizationTrialRequestResource = null;
        OrganizationTrialRequestResource response = api.submitTrialRequest(id, organizationTrialRequestResource);

        // TODO: test validations
    }
    
}
