/*
 * Katalon TestOps API reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.katalon.testops.api.api;

import com.katalon.testops.api.model.ProjectConfigurationResource;
import com.katalon.testops.api.model.TimeZoneResource;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProjectConfigurationResourceControllerApi
 */
@Ignore
public class ProjectConfigurationResourceControllerApiTest {

    private final ProjectConfigurationResourceControllerApi api = new ProjectConfigurationResourceControllerApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void get14Test() {
        Long id = null;
        String name = null;
        ProjectConfigurationResource response = api.get14(id, name);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listTimeZonesTest() {
        List<TimeZoneResource> response = api.listTimeZones();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void update8Test() {
        Long id = null;
        ProjectConfigurationResource projectConfigurationResource = null;
        ProjectConfigurationResource response = api.update8(id, projectConfigurationResource);

        // TODO: test validations
    }
    
}
