/*
 * Katalon TestOps API reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.katalon.testops.api.api;

import com.katalon.testops.api.model.ReleaseResource;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ReleaseApi
 */
@Ignore
public class ReleaseApiTest {

    private final ReleaseApi api = new ReleaseApi();

    
    /**
     * Open or close a Release. Returns the updated Release detail.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void activeReleaseTest() {
        Long id = null;
        Boolean closed = null;
        ReleaseResource response = api.activeRelease(id, closed);

        // TODO: test validations
    }
    
    /**
     * Creates or updates a Release. Returns the Release details.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createOrUpdate1Test() {
        ReleaseResource releaseResource = null;
        ReleaseResource response = api.createOrUpdate1(releaseResource);

        // TODO: test validations
    }
    
    /**
     * Deletes a Release. Returns the Release details.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void delete3Test() {
        Long id = null;
        ReleaseResource response = api.delete3(id);

        // TODO: test validations
    }
    
    /**
     * Updates a Release. Returns the Release details.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void update3Test() {
        ReleaseResource releaseResource = null;
        ReleaseResource response = api.update3(releaseResource);

        // TODO: test validations
    }
    
}
