/*
 * Katalon TestOps API reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.katalon.testops.api.api;

import com.katalon.testops.api.model.RunConfigurationResource;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TestPlanApi
 */
@Ignore
public class TestPlanApiTest {

    private final TestPlanApi api = new TestPlanApi();

    
    /**
     * Creates and triggers a sample Test Plan. Returns the created Test Plan detail.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createAndTriggerSampleTest() {
        RunConfigurationResource runConfigurationResource = null;
        RunConfigurationResource response = api.createAndTriggerSample(runConfigurationResource);

        // TODO: test validations
    }
    
    /**
     * Creates or updates a Test Plan. Returns the Test Plan detail.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createOrUpdateConfigurationTest() {
        RunConfigurationResource runConfigurationResource = null;
        Boolean verifyRunConfiguration = null;
        RunConfigurationResource response = api.createOrUpdateConfiguration(runConfigurationResource, verifyRunConfiguration);

        // TODO: test validations
    }
    
    /**
     * Deletes a Test Plan. Returns the deleted Test Plan detail.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void delete5Test() {
        Long id = null;
        RunConfigurationResource response = api.delete5(id);

        // TODO: test validations
    }
    
    /**
     * Link an Run Configuration to a Release. Returns the updated Run Configuration detail.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void linkRelease1Test() {
        Long id = null;
        Long projectId = null;
        Long releaseId = null;
        RunConfigurationResource response = api.linkRelease1(id, projectId, releaseId);

        // TODO: test validations
    }
    
    /**
     * Unlink an Run Configuration to a Release. Returns the updated Run Configuration detail.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void unlinkRelease1Test() {
        Long id = null;
        RunConfigurationResource response = api.unlinkRelease1(id);

        // TODO: test validations
    }
    
}
