/*
 * Katalon TestOps API reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.katalon.testops.api.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ConfigResource
 */
public class ConfigResourceTest {
    private final ConfigResource model = new ConfigResource();

    /**
     * Model tests for ConfigResource
     */
    @Test
    public void testConfigResource() {
        // TODO: test ConfigResource
    }

    /**
     * Test the property 'webSocketUrl'
     */
    @Test
    public void webSocketUrlTest() {
        // TODO: test webSocketUrl
    }

    /**
     * Test the property 'storeUrl'
     */
    @Test
    public void storeUrlTest() {
        // TODO: test storeUrl
    }

    /**
     * Test the property 'profiles'
     */
    @Test
    public void profilesTest() {
        // TODO: test profiles
    }

    /**
     * Test the property 'stripePublicApi'
     */
    @Test
    public void stripePublicApiTest() {
        // TODO: test stripePublicApi
    }

    /**
     * Test the property 'buildVersion'
     */
    @Test
    public void buildVersionTest() {
        // TODO: test buildVersion
    }

    /**
     * Test the property 'commitId'
     */
    @Test
    public void commitIdTest() {
        // TODO: test commitId
    }

    /**
     * Test the property 'sentryDsn'
     */
    @Test
    public void sentryDsnTest() {
        // TODO: test sentryDsn
    }

    /**
     * Test the property 'sentryEnv'
     */
    @Test
    public void sentryEnvTest() {
        // TODO: test sentryEnv
    }

    /**
     * Test the property 'serverUrl'
     */
    @Test
    public void serverUrlTest() {
        // TODO: test serverUrl
    }

    /**
     * Test the property 'maxExecutionComparison'
     */
    @Test
    public void maxExecutionComparisonTest() {
        // TODO: test maxExecutionComparison
    }

    /**
     * Test the property 'maxExecutionDownload'
     */
    @Test
    public void maxExecutionDownloadTest() {
        // TODO: test maxExecutionDownload
    }

    /**
     * Test the property 'agentDownloadUrls'
     */
    @Test
    public void agentDownloadUrlsTest() {
        // TODO: test agentDownloadUrls
    }

    /**
     * Test the property 'subDomainPattern'
     */
    @Test
    public void subDomainPatternTest() {
        // TODO: test subDomainPattern
    }

    /**
     * Test the property 'cancellationSurveyUrl'
     */
    @Test
    public void cancellationSurveyUrlTest() {
        // TODO: test cancellationSurveyUrl
    }

    /**
     * Test the property 'advancedFeatureEnabled'
     */
    @Test
    public void advancedFeatureEnabledTest() {
        // TODO: test advancedFeatureEnabled
    }

    /**
     * Test the property 'usingSubDomain'
     */
    @Test
    public void usingSubDomainTest() {
        // TODO: test usingSubDomain
    }

}
