/*
 * Katalon TestOps API reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.katalon.testops.api.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.katalon.testops.api.model.ExecutionTestSuiteResource;
import com.katalon.testops.api.model.ProjectResource;
import com.katalon.testops.api.model.ReleaseResource;
import com.katalon.testops.api.model.TestSuiteCollectionEntityResource;
import com.katalon.testops.api.model.UserResource;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ExecutionResource
 */
public class ExecutionResourceTest {
    private final ExecutionResource model = new ExecutionResource();

    /**
     * Model tests for ExecutionResource
     */
    @Test
    public void testExecutionResource() {
        // TODO: test ExecutionResource
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'startTime'
     */
    @Test
    public void startTimeTest() {
        // TODO: test startTime
    }

    /**
     * Test the property 'endTime'
     */
    @Test
    public void endTimeTest() {
        // TODO: test endTime
    }

    /**
     * Test the property 'duration'
     */
    @Test
    public void durationTest() {
        // TODO: test duration
    }

    /**
     * Test the property 'elapsedDuration'
     */
    @Test
    public void elapsedDurationTest() {
        // TODO: test elapsedDuration
    }

    /**
     * Test the property 'totalTests'
     */
    @Test
    public void totalTestsTest() {
        // TODO: test totalTests
    }

    /**
     * Test the property 'totalPassedTests'
     */
    @Test
    public void totalPassedTestsTest() {
        // TODO: test totalPassedTests
    }

    /**
     * Test the property 'totalFailedTests'
     */
    @Test
    public void totalFailedTestsTest() {
        // TODO: test totalFailedTests
    }

    /**
     * Test the property 'totalErrorTests'
     */
    @Test
    public void totalErrorTestsTest() {
        // TODO: test totalErrorTests
    }

    /**
     * Test the property 'totalIncompleteTests'
     */
    @Test
    public void totalIncompleteTestsTest() {
        // TODO: test totalIncompleteTests
    }

    /**
     * Test the property 'totalDiffTests'
     */
    @Test
    public void totalDiffTestsTest() {
        // TODO: test totalDiffTests
    }

    /**
     * Test the property 'totalDiffPassedTests'
     */
    @Test
    public void totalDiffPassedTestsTest() {
        // TODO: test totalDiffPassedTests
    }

    /**
     * Test the property 'totalDiffFailedTests'
     */
    @Test
    public void totalDiffFailedTestsTest() {
        // TODO: test totalDiffFailedTests
    }

    /**
     * Test the property 'totalDiffErrorTests'
     */
    @Test
    public void totalDiffErrorTestsTest() {
        // TODO: test totalDiffErrorTests
    }

    /**
     * Test the property 'totalDiffIncompleteTests'
     */
    @Test
    public void totalDiffIncompleteTestsTest() {
        // TODO: test totalDiffIncompleteTests
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'projectId'
     */
    @Test
    public void projectIdTest() {
        // TODO: test projectId
    }

    /**
     * Test the property 'project'
     */
    @Test
    public void projectTest() {
        // TODO: test project
    }

    /**
     * Test the property 'buildId'
     */
    @Test
    public void buildIdTest() {
        // TODO: test buildId
    }

    /**
     * Test the property 'order'
     */
    @Test
    public void orderTest() {
        // TODO: test order
    }

    /**
     * Test the property 'executionStage'
     */
    @Test
    public void executionStageTest() {
        // TODO: test executionStage
    }

    /**
     * Test the property 'webUrl'
     */
    @Test
    public void webUrlTest() {
        // TODO: test webUrl
    }

    /**
     * Test the property 'testSuiteCollections'
     */
    @Test
    public void testSuiteCollectionsTest() {
        // TODO: test testSuiteCollections
    }

    /**
     * Test the property 'executionTestSuiteResources'
     */
    @Test
    public void executionTestSuiteResourcesTest() {
        // TODO: test executionTestSuiteResources
    }

    /**
     * Test the property 'release'
     */
    @Test
    public void releaseTest() {
        // TODO: test release
    }

    /**
     * Test the property 'hasComment'
     */
    @Test
    public void hasCommentTest() {
        // TODO: test hasComment
    }

    /**
     * Test the property 'user'
     */
    @Test
    public void userTest() {
        // TODO: test user
    }

    /**
     * Test the property 'sessionId'
     */
    @Test
    public void sessionIdTest() {
        // TODO: test sessionId
    }

    /**
     * Test the property 'buildLabel'
     */
    @Test
    public void buildLabelTest() {
        // TODO: test buildLabel
    }

    /**
     * Test the property 'buildUrl'
     */
    @Test
    public void buildUrlTest() {
        // TODO: test buildUrl
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

}
