/*
 * Katalon TestOps API reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.katalon.testops.api.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.katalon.testops.api.model.ExecutionTestResultResource;
import com.katalon.testops.api.model.TestObjectResource;
import com.katalon.testops.api.model.UploadFileResource;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ExecutionRequestResource
 */
public class ExecutionRequestResourceTest {
    private final ExecutionRequestResource model = new ExecutionRequestResource();

    /**
     * Model tests for ExecutionRequestResource
     */
    @Test
    public void testExecutionRequestResource() {
        // TODO: test ExecutionRequestResource
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'executionTestResult'
     */
    @Test
    public void executionTestResultTest() {
        // TODO: test executionTestResult
    }

    /**
     * Test the property '_object'
     */
    @Test
    public void _objectTest() {
        // TODO: test _object
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'abnormal'
     */
    @Test
    public void abnormalTest() {
        // TODO: test abnormal
    }

    /**
     * Test the property 'percentAbnormal'
     */
    @Test
    public void percentAbnormalTest() {
        // TODO: test percentAbnormal
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'method'
     */
    @Test
    public void methodTest() {
        // TODO: test method
    }

    /**
     * Test the property 'statusText'
     */
    @Test
    public void statusTextTest() {
        // TODO: test statusText
    }

    /**
     * Test the property 'time'
     */
    @Test
    public void timeTest() {
        // TODO: test time
    }

    /**
     * Test the property 'size'
     */
    @Test
    public void sizeTest() {
        // TODO: test size
    }

    /**
     * Test the property 'uploadFile'
     */
    @Test
    public void uploadFileTest() {
        // TODO: test uploadFile
    }

    /**
     * Test the property 'startedAt'
     */
    @Test
    public void startedAtTest() {
        // TODO: test startedAt
    }

}
