/*
 * Katalon TestOps API reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.katalon.testops.api.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ExecutionTestCaseResource
 */
public class ExecutionTestCaseResourceTest {
    private final ExecutionTestCaseResource model = new ExecutionTestCaseResource();

    /**
     * Model tests for ExecutionTestCaseResource
     */
    @Test
    public void testExecutionTestCaseResource() {
        // TODO: test ExecutionTestCaseResource
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'startTime'
     */
    @Test
    public void startTimeTest() {
        // TODO: test startTime
    }

    /**
     * Test the property 'endTime'
     */
    @Test
    public void endTimeTest() {
        // TODO: test endTime
    }

    /**
     * Test the property 'duration'
     */
    @Test
    public void durationTest() {
        // TODO: test duration
    }

    /**
     * Test the property 'elapsedDuration'
     */
    @Test
    public void elapsedDurationTest() {
        // TODO: test elapsedDuration
    }

    /**
     * Test the property 'totalTests'
     */
    @Test
    public void totalTestsTest() {
        // TODO: test totalTests
    }

    /**
     * Test the property 'totalPassedTests'
     */
    @Test
    public void totalPassedTestsTest() {
        // TODO: test totalPassedTests
    }

    /**
     * Test the property 'totalFailedTests'
     */
    @Test
    public void totalFailedTestsTest() {
        // TODO: test totalFailedTests
    }

    /**
     * Test the property 'totalErrorTests'
     */
    @Test
    public void totalErrorTestsTest() {
        // TODO: test totalErrorTests
    }

    /**
     * Test the property 'totalIncompleteTests'
     */
    @Test
    public void totalIncompleteTestsTest() {
        // TODO: test totalIncompleteTests
    }

    /**
     * Test the property 'totalDiffTests'
     */
    @Test
    public void totalDiffTestsTest() {
        // TODO: test totalDiffTests
    }

    /**
     * Test the property 'totalDiffPassedTests'
     */
    @Test
    public void totalDiffPassedTestsTest() {
        // TODO: test totalDiffPassedTests
    }

    /**
     * Test the property 'totalDiffFailedTests'
     */
    @Test
    public void totalDiffFailedTestsTest() {
        // TODO: test totalDiffFailedTests
    }

    /**
     * Test the property 'totalDiffErrorTests'
     */
    @Test
    public void totalDiffErrorTestsTest() {
        // TODO: test totalDiffErrorTests
    }

    /**
     * Test the property 'totalDiffIncompleteTests'
     */
    @Test
    public void totalDiffIncompleteTestsTest() {
        // TODO: test totalDiffIncompleteTests
    }

    /**
     * Test the property 'executionId'
     */
    @Test
    public void executionIdTest() {
        // TODO: test executionId
    }

    /**
     * Test the property 'executionOrder'
     */
    @Test
    public void executionOrderTest() {
        // TODO: test executionOrder
    }

    /**
     * Test the property 'testCaseId'
     */
    @Test
    public void testCaseIdTest() {
        // TODO: test testCaseId
    }

    /**
     * Test the property 'projectId'
     */
    @Test
    public void projectIdTest() {
        // TODO: test projectId
    }

}
