/*
 * Katalon TestOps API reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.katalon.testops.api.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for IncidentExecutionTestResultResource
 */
public class IncidentExecutionTestResultResourceTest {
    private final IncidentExecutionTestResultResource model = new IncidentExecutionTestResultResource();

    /**
     * Model tests for IncidentExecutionTestResultResource
     */
    @Test
    public void testIncidentExecutionTestResultResource() {
        // TODO: test IncidentExecutionTestResultResource
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'incidentId'
     */
    @Test
    public void incidentIdTest() {
        // TODO: test incidentId
    }

    /**
     * Test the property 'projectId'
     */
    @Test
    public void projectIdTest() {
        // TODO: test projectId
    }

    /**
     * Test the property 'incidentOrder'
     */
    @Test
    public void incidentOrderTest() {
        // TODO: test incidentOrder
    }

    /**
     * Test the property 'executionTestResultId'
     */
    @Test
    public void executionTestResultIdTest() {
        // TODO: test executionTestResultId
    }

}
