/*
 * Katalon TestOps API reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.katalon.testops.api.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.katalon.testops.api.model.ReleaseResource;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ReleaseStatisticsResource
 */
public class ReleaseStatisticsResourceTest {
    private final ReleaseStatisticsResource model = new ReleaseStatisticsResource();

    /**
     * Model tests for ReleaseStatisticsResource
     */
    @Test
    public void testReleaseStatisticsResource() {
        // TODO: test ReleaseStatisticsResource
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'release'
     */
    @Test
    public void releaseTest() {
        // TODO: test release
    }

    /**
     * Test the property 'totalPassed'
     */
    @Test
    public void totalPassedTest() {
        // TODO: test totalPassed
    }

    /**
     * Test the property 'totalFailed'
     */
    @Test
    public void totalFailedTest() {
        // TODO: test totalFailed
    }

    /**
     * Test the property 'totalExecution'
     */
    @Test
    public void totalExecutionTest() {
        // TODO: test totalExecution
    }

}
