/*
 * Katalon TestOps API reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.katalon.testops.api.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.katalon.testops.api.model.AgentResource;
import com.katalon.testops.api.model.CircleCIAgentResource;
import com.katalon.testops.api.model.JobResource;
import com.katalon.testops.api.model.K8SAgentResource;
import com.katalon.testops.api.model.ReleaseResource;
import com.katalon.testops.api.model.SchedulerResource;
import com.katalon.testops.api.model.TestProjectResource;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for RunConfigurationResource
 */
public class RunConfigurationResourceTest {
    private final RunConfigurationResource model = new RunConfigurationResource();

    /**
     * Model tests for RunConfigurationResource
     */
    @Test
    public void testRunConfigurationResource() {
        // TODO: test RunConfigurationResource
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'command'
     */
    @Test
    public void commandTest() {
        // TODO: test command
    }

    /**
     * Test the property 'projectId'
     */
    @Test
    public void projectIdTest() {
        // TODO: test projectId
    }

    /**
     * Test the property 'teamId'
     */
    @Test
    public void teamIdTest() {
        // TODO: test teamId
    }

    /**
     * Test the property 'testProjectId'
     */
    @Test
    public void testProjectIdTest() {
        // TODO: test testProjectId
    }

    /**
     * Test the property 'testSuiteCollectionId'
     */
    @Test
    public void testSuiteCollectionIdTest() {
        // TODO: test testSuiteCollectionId
    }

    /**
     * Test the property 'timeOut'
     */
    @Test
    public void timeOutTest() {
        // TODO: test timeOut
    }

    /**
     * Test the property 'configType'
     */
    @Test
    public void configTypeTest() {
        // TODO: test configType
    }

    /**
     * Test the property 'testProject'
     */
    @Test
    public void testProjectTest() {
        // TODO: test testProject
    }

    /**
     * Test the property 'agents'
     */
    @Test
    public void agentsTest() {
        // TODO: test agents
    }

    /**
     * Test the property 'k8sAgents'
     */
    @Test
    public void k8sAgentsTest() {
        // TODO: test k8sAgents
    }

    /**
     * Test the property 'circleCIAgents'
     */
    @Test
    public void circleCIAgentsTest() {
        // TODO: test circleCIAgents
    }

    /**
     * Test the property 'cloudType'
     */
    @Test
    public void cloudTypeTest() {
        // TODO: test cloudType
    }

    /**
     * Test the property 'latestJob'
     */
    @Test
    public void latestJobTest() {
        // TODO: test latestJob
    }

    /**
     * Test the property 'genericCommand'
     */
    @Test
    public void genericCommandTest() {
        // TODO: test genericCommand
    }

    /**
     * Test the property 'ksVersion'
     */
    @Test
    public void ksVersionTest() {
        // TODO: test ksVersion
    }

    /**
     * Test the property 'ksLocation'
     */
    @Test
    public void ksLocationTest() {
        // TODO: test ksLocation
    }

    /**
     * Test the property 'nextRunScheduler'
     */
    @Test
    public void nextRunSchedulerTest() {
        // TODO: test nextRunScheduler
    }

    /**
     * Test the property 'release'
     */
    @Test
    public void releaseTest() {
        // TODO: test release
    }

}
