/*
 * Katalon TestOps API reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.katalon.testops.api.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SearchConfigResource
 */
public class SearchConfigResourceTest {
    private final SearchConfigResource model = new SearchConfigResource();

    /**
     * Model tests for SearchConfigResource
     */
    @Test
    public void testSearchConfigResource() {
        // TODO: test SearchConfigResource
    }

    /**
     * Test the property 'filterConfig'
     */
    @Test
    public void filterConfigTest() {
        // TODO: test filterConfig
    }

    /**
     * Test the property 'sortDefault'
     */
    @Test
    public void sortDefaultTest() {
        // TODO: test sortDefault
    }

    /**
     * Test the property 'sortConfig'
     */
    @Test
    public void sortConfigTest() {
        // TODO: test sortConfig
    }

}
