/*
 * Katalon TestOps API reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.katalon.testops.api.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.katalon.testops.api.model.ExecutionTestCaseResource;
import com.katalon.testops.api.model.ExecutionTestResultResource;
import com.katalon.testops.api.model.ExternalIssueResource;
import com.katalon.testops.api.model.ProjectResource;
import com.katalon.testops.api.model.TestCasePlatformStatisticsResource;
import com.katalon.testops.api.model.UserResource;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TestCaseResource
 */
public class TestCaseResourceTest {
    private final TestCaseResource model = new TestCaseResource();

    /**
     * Model tests for TestCaseResource
     */
    @Test
    public void testTestCaseResource() {
        // TODO: test TestCaseResource
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'path'
     */
    @Test
    public void pathTest() {
        // TODO: test path
    }

    /**
     * Test the property 'previousStatus'
     */
    @Test
    public void previousStatusTest() {
        // TODO: test previousStatus
    }

    /**
     * Test the property 'alias'
     */
    @Test
    public void aliasTest() {
        // TODO: test alias
    }

    /**
     * Test the property 'testModuleId'
     */
    @Test
    public void testModuleIdTest() {
        // TODO: test testModuleId
    }

    /**
     * Test the property 'webUrl'
     */
    @Test
    public void webUrlTest() {
        // TODO: test webUrl
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'project'
     */
    @Test
    public void projectTest() {
        // TODO: test project
    }

    /**
     * Test the property 'lastExecutionTestCase'
     */
    @Test
    public void lastExecutionTestCaseTest() {
        // TODO: test lastExecutionTestCase
    }

    /**
     * Test the property 'externalIssues'
     */
    @Test
    public void externalIssuesTest() {
        // TODO: test externalIssues
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'averageDuration'
     */
    @Test
    public void averageDurationTest() {
        // TODO: test averageDuration
    }

    /**
     * Test the property 'maxDuration'
     */
    @Test
    public void maxDurationTest() {
        // TODO: test maxDuration
    }

    /**
     * Test the property 'minDuration'
     */
    @Test
    public void minDurationTest() {
        // TODO: test minDuration
    }

    /**
     * Test the property 'executionTestResults'
     */
    @Test
    public void executionTestResultsTest() {
        // TODO: test executionTestResults
    }

    /**
     * Test the property 'flakiness'
     */
    @Test
    public void flakinessTest() {
        // TODO: test flakiness
    }

    /**
     * Test the property 'platformStatistics'
     */
    @Test
    public void platformStatisticsTest() {
        // TODO: test platformStatistics
    }

    /**
     * Test the property 'maintainer'
     */
    @Test
    public void maintainerTest() {
        // TODO: test maintainer
    }

    /**
     * Test the property 'urlId'
     */
    @Test
    public void urlIdTest() {
        // TODO: test urlId
    }

}
