/*
 * Katalon TestOps API reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.katalon.testops.api.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.katalon.testops.api.model.PlatformResource;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TestCasePlatformStatisticsResource
 */
public class TestCasePlatformStatisticsResourceTest {
    private final TestCasePlatformStatisticsResource model = new TestCasePlatformStatisticsResource();

    /**
     * Model tests for TestCasePlatformStatisticsResource
     */
    @Test
    public void testTestCasePlatformStatisticsResource() {
        // TODO: test TestCasePlatformStatisticsResource
    }

    /**
     * Test the property 'totalTests'
     */
    @Test
    public void totalTestsTest() {
        // TODO: test totalTests
    }

    /**
     * Test the property 'totalPassedTests'
     */
    @Test
    public void totalPassedTestsTest() {
        // TODO: test totalPassedTests
    }

    /**
     * Test the property 'totalFailedTests'
     */
    @Test
    public void totalFailedTestsTest() {
        // TODO: test totalFailedTests
    }

    /**
     * Test the property 'totalErrorTests'
     */
    @Test
    public void totalErrorTestsTest() {
        // TODO: test totalErrorTests
    }

    /**
     * Test the property 'totalIncompleteTests'
     */
    @Test
    public void totalIncompleteTestsTest() {
        // TODO: test totalIncompleteTests
    }

    /**
     * Test the property 'platform'
     */
    @Test
    public void platformTest() {
        // TODO: test platform
    }

    /**
     * Test the property 'platformId'
     */
    @Test
    public void platformIdTest() {
        // TODO: test platformId
    }

}
