/*
 * Katalon TestOps API reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.katalon.testops.api.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.katalon.testops.api.model.TimeZoneResourceOffsetRulesTransitionRules;
import com.katalon.testops.api.model.TimeZoneResourceOffsetRulesTransitions;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TimeZoneResourceOffsetRules
 */
public class TimeZoneResourceOffsetRulesTest {
    private final TimeZoneResourceOffsetRules model = new TimeZoneResourceOffsetRules();

    /**
     * Model tests for TimeZoneResourceOffsetRules
     */
    @Test
    public void testTimeZoneResourceOffsetRules() {
        // TODO: test TimeZoneResourceOffsetRules
    }

    /**
     * Test the property 'fixedOffset'
     */
    @Test
    public void fixedOffsetTest() {
        // TODO: test fixedOffset
    }

    /**
     * Test the property 'transitions'
     */
    @Test
    public void transitionsTest() {
        // TODO: test transitions
    }

    /**
     * Test the property 'transitionRules'
     */
    @Test
    public void transitionRulesTest() {
        // TODO: test transitionRules
    }

}
