/*
 * Katalon TestOps API reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.katalon.testops.api.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TimeZoneResourceOffsetRulesTransitionRules
 */
public class TimeZoneResourceOffsetRulesTransitionRulesTest {
    private final TimeZoneResourceOffsetRulesTransitionRules model = new TimeZoneResourceOffsetRulesTransitionRules();

    /**
     * Model tests for TimeZoneResourceOffsetRulesTransitionRules
     */
    @Test
    public void testTimeZoneResourceOffsetRulesTransitionRules() {
        // TODO: test TimeZoneResourceOffsetRulesTransitionRules
    }

    /**
     * Test the property 'month'
     */
    @Test
    public void monthTest() {
        // TODO: test month
    }

    /**
     * Test the property 'timeDefinition'
     */
    @Test
    public void timeDefinitionTest() {
        // TODO: test timeDefinition
    }

    /**
     * Test the property 'localTime'
     */
    @Test
    public void localTimeTest() {
        // TODO: test localTime
    }

    /**
     * Test the property 'dayOfWeek'
     */
    @Test
    public void dayOfWeekTest() {
        // TODO: test dayOfWeek
    }

    /**
     * Test the property 'dayOfMonthIndicator'
     */
    @Test
    public void dayOfMonthIndicatorTest() {
        // TODO: test dayOfMonthIndicator
    }

    /**
     * Test the property 'midnightEndOfDay'
     */
    @Test
    public void midnightEndOfDayTest() {
        // TODO: test midnightEndOfDay
    }

}
