/*
 * Katalon TestOps API reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.katalon.testops.api.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for UploadBatchFileResource
 */
public class UploadBatchFileResourceTest {
    private final UploadBatchFileResource model = new UploadBatchFileResource();

    /**
     * Model tests for UploadBatchFileResource
     */
    @Test
    public void testUploadBatchFileResource() {
        // TODO: test UploadBatchFileResource
    }

    /**
     * Test the property 'folderPath'
     */
    @Test
    public void folderPathTest() {
        // TODO: test folderPath
    }

    /**
     * Test the property 'end'
     */
    @Test
    public void endTest() {
        // TODO: test end
    }

    /**
     * Test the property 'fileName'
     */
    @Test
    public void fileNameTest() {
        // TODO: test fileName
    }

    /**
     * Test the property 'uploadedPath'
     */
    @Test
    public void uploadedPathTest() {
        // TODO: test uploadedPath
    }

}
