/*
 * Katalon TestOps API reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.katalon.testops.api.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for UserSettingResource
 */
public class UserSettingResourceTest {
    private final UserSettingResource model = new UserSettingResource();

    /**
     * Model tests for UserSettingResource
     */
    @Test
    public void testUserSettingResource() {
        // TODO: test UserSettingResource
    }

    /**
     * Test the property 'mailJobStart'
     */
    @Test
    public void mailJobStartTest() {
        // TODO: test mailJobStart
    }

    /**
     * Test the property 'mailJobEnd'
     */
    @Test
    public void mailJobEndTest() {
        // TODO: test mailJobEnd
    }

    /**
     * Test the property 'mailExecution'
     */
    @Test
    public void mailExecutionTest() {
        // TODO: test mailExecution
    }

    /**
     * Test the property 'mailExecutionStatus'
     */
    @Test
    public void mailExecutionStatusTest() {
        // TODO: test mailExecutionStatus
    }

    /**
     * Test the property 'mailWeeklyUpdate'
     */
    @Test
    public void mailWeeklyUpdateTest() {
        // TODO: test mailWeeklyUpdate
    }

}
