/*
 * Katalon TestOps API reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.katalon.testops.api;

import com.katalon.testops.model.FileResource;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for FileApi
 */
@Ignore
public class FileApiTest {

    private final FileApi api = new FileApi();

    /**
     * Downloads a file.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void download2Test() {
        Long id = null;
        api.download2(id);

        // TODO: test validations
    }
    /**
     * Returns an upload URL.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUploadUrlTest() {
        Long projectId = null;
        FileResource response = api.getUploadUrl(projectId);

        // TODO: test validations
    }
    /**
     * Returns multiple upload URLs.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUploadUrlsTest() {
        Long projectId = null;
        Long numberUrl = null;
        List<FileResource> response = api.getUploadUrls(projectId, numberUrl);

        // TODO: test validations
    }
}
