/*
 * Katalon TestOps API reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.katalon.testops.api;

import com.katalon.testops.model.ProjectConfigurationResource;
import com.katalon.testops.model.TimeZoneResource;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProjectConfigurationResourceControllerApi
 */
@Ignore
public class ProjectConfigurationResourceControllerApiTest {

    private final ProjectConfigurationResourceControllerApi api = new ProjectConfigurationResourceControllerApi();

    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void get14Test() {
        Long id = null;
        String name = null;
        ProjectConfigurationResource response = api.get14(id, name);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listTimeZonesTest() {
        List<TimeZoneResource> response = api.listTimeZones();

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void update8Test() {
        ProjectConfigurationResource body = null;
        Long id = null;
        ProjectConfigurationResource response = api.update8(body, id);

        // TODO: test validations
    }
}
